"""Stride: 10-year financial model.

Every table in 03-financial-model.md and 04-capital-and-valuation.md is
generated by this script. Nothing in those documents is hand-typed, so the
arithmetic is reproducible and an examiner can change one assumption and see
the whole model move:

    python business-plan/model.py            # print all tables
    python business-plan/model.py --write    # regenerate the markdown docs

Currency is EUR throughout (the company is Spanish). Note the product currently
stores money in `*_eur` columns, as this model does.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field

YEARS = list(range(1, 11))  # Y1 = 2027 .. Y10 = 2036

# Ten years, not seven. At Y7 the company is still compounding above 50%, so a
# perpetuity-growth terminal value placed there does most of the valuation work
# and does it badly. Extending to Y10 lets growth decelerate inside the explicit
# forecast, which is where it belongs.


# ─────────────────────────────────────────────────────────────────────────────
# Assumptions. Every number a reader might argue with lives here.
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Segment:
    """One market segment. The two differ in kind, not just in size, see
    business-plan/06-market-strategy.md and sport_index.py.

    NICHE (market creation): no agent exists. Fans are usually participants in
    the same sport, so conversion is high and they pay for knowledge. Smaller
    followings, cheaper to acquire, smaller sponsorship deals.

    POPULAR (disintermediation): an agent already takes 10-20%. Larger
    followings but lower conversion: a football fan follows a club, not a
    training plan. Expensive to acquire because there is a relationship to
    displace, but the deals are much larger.
    """
    name: str
    monetise_rate: list[float]      # share of athletes who turn on fan monetisation
    fans_per_athlete: list[int]     # paying fans per monetising athlete, at YEAR END
    fan_arpu_month: list[float]
    fan_churn_month: list[float]    # monthly, compounds, see fan_path()
    athlete_churn_year: list[float]  # annual; drives gross adds, and therefore CAC
    deal_rate: list[float]          # share of athletes landing >=1 deal a year
    deals_per_athlete: list[float]
    avg_deal_eur: list[int]
    cac_eur: list[int]
    # An athlete cannot recruit unlimited new paying fans: their audience is
    # finite and they can only convert so much of it per year. Without this
    # ceiling the model treats the year-end target as reachable at ANY churn
    # rate, which makes high churn *raise* revenue, more churn simply means
    # more gross adds through the year, so average fans go up. That is
    # backwards, and this cap is what makes churn bite.
    max_fan_adds_per_athlete_year: list[int]


NICHE = Segment(
    name="niche",
    #: Zero in Y1: the fan tier is B2, behind the payment rail and sponsorship
    #: monetisation, so the first subscription charge lands in Y2. See the
    #: launch plan in section 5.11.
    monetise_rate=[0.00, 0.32, 0.37, 0.41, 0.44, 0.46, 0.48, 0.49, 0.50, 0.50],
    fans_per_athlete=[20, 22, 25, 28, 30, 32, 34, 35, 36, 37],
    fan_arpu_month=[8.00, 8.30, 8.60, 8.80, 9.00, 9.10, 9.20, 9.30, 9.40, 9.50],
    # Niche fans churn less: they subscribed for knowledge, and training is a
    # habit rather than an impulse. Seasons also create natural renewal points.
    fan_churn_month=[0.090, 0.085, 0.080, 0.075, 0.070, 0.065, 0.060, 0.058, 0.056, 0.055],
    athlete_churn_year=[0.30, 0.27, 0.24, 0.22, 0.20, 0.19, 0.18, 0.17, 0.16, 0.16],
    deal_rate=[0.05, 0.07, 0.09, 0.11, 0.13, 0.15, 0.16, 0.17, 0.17, 0.18],
    deals_per_athlete=[1.1, 1.2, 1.3, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 2.0],
    avg_deal_eur=[900, 1_050, 1_200, 1_350, 1_500, 1_600, 1_700, 1_800, 1_900, 2_000],
    cac_eur=[16, 18, 21, 24, 27, 30, 32, 34, 35, 36],
    max_fan_adds_per_athlete_year=[30, 33, 36, 40, 43, 45, 47, 49, 50, 52],
)

POPULAR = Segment(
    name="popular",
    #: Zero in Y1, for the same reason as niche: fan monetisation is B2.
    monetise_rate=[0.00, 0.17, 0.20, 0.23, 0.26, 0.28, 0.30, 0.31, 0.32, 0.32],
    fans_per_athlete=[26, 29, 32, 35, 38, 41, 44, 46, 47, 48],
    fan_arpu_month=[7.00, 7.20, 7.40, 7.60, 7.80, 7.90, 8.00, 8.10, 8.20, 8.30],
    # Popular-sport fans churn harder: an impulse follow after a result, with
    # many competing ways to consume the same athlete for free.
    fan_churn_month=[0.130, 0.125, 0.120, 0.110, 0.105, 0.100, 0.090, 0.088, 0.086, 0.085],
    athlete_churn_year=[0.35, 0.32, 0.30, 0.27, 0.25, 0.23, 0.22, 0.21, 0.21, 0.20],
    deal_rate=[0.14, 0.17, 0.20, 0.24, 0.27, 0.29, 0.30, 0.31, 0.31, 0.32],
    deals_per_athlete=[1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.4, 2.5, 2.5, 2.6],
    avg_deal_eur=[2_200, 2_500, 2_800, 3_100, 3_400, 3_700, 4_000, 4_200, 4_400, 4_600],
    cac_eur=[40, 46, 53, 60, 67, 73, 78, 82, 85, 88],
    max_fan_adds_per_athlete_year=[38, 42, 46, 50, 54, 58, 62, 65, 67, 69],
)


@dataclass
class Assumptions:
    # ---- demand side -------------------------------------------------------
    # Slowed deliberately, and the old curve did not fit the plan's own market.
    # SAM in section 3.3 is ~55,000 athletes; the previous ramp reached 52,000 by
    # Y7 (95% of it) and 85,000 by Y10 -- 155% of the entire addressable market.
    # The draft flagged the Y7 number as "close to the whole SAM" and never
    # mentioned that Y10 went straight through it.
    #
    # This curve reaches 6,300 by Y7 (11% of SAM) and 8,500 by Y10 (15%). It
    # also matches the go-to-market the plan actually describes: club-by-club,
    # race-day, federation-led acquisition in sceptical communities, which is
    # slow by construction. Growth decelerates smoothly -- 3.0x, 2.3x, 1.6x,
    # 1.4x, 1.3x, 1.2x -- from a believable multiple rather than 4.5x in the
    # first year after launch.
    #: Moderated 1 Oct 2026, from a Y10 of 40,000. The comparable set
    #: (Sponsoo 13 people in 11 years, OpenSponsorship 23 in 12) says a
    #: two sided sponsorship marketplace does not reach tens of thousands
    #: of athletes on a founder led cost base, and the plan should not
    #: promise a company its founder does not intend to run.
    athletes: list[int] = field(default_factory=lambda: [250, 750, 1_700, 2_800, 4_000, 5_200, 6_300, 7_200, 7_900, 8_500])
    # Niche first (no incumbent, acute need), popular entering from Y3 once the
    # niche cohort's earnings make the disintermediation pitch quantified.
    niche_share: list[float] = field(default_factory=lambda: [0.95, 0.92, 0.80, 0.68, 0.58, 0.50, 0.45, 0.43, 0.42, 0.41])
    segments: list[Segment] = field(default_factory=lambda: [NICHE, POPULAR])

    # one-off fan spend (unlocks + tips) as a multiple of subscription GMV
    ppv_tips_multiple: float = 0.35

    # ---- sponsor SaaS ------------------------------------------------------
    # Sponsors follow athlete supply -- they arrive for the roster -- so this
    # curve is slowed in step with `athletes`. Left at the old numbers it would
    # have modelled demand densifying against a supply side half the size.
    #: Scaled with the athlete base: a sponsor subscribes for access to
    #: supply, so the two cannot be set independently.
    sponsors: list[int] = field(default_factory=lambda: [18, 55, 125, 240, 380, 510, 620, 710, 790, 850])
    sponsor_paid_rate: list[float] = field(default_factory=lambda: [0.10, 0.14, 0.17, 0.19, 0.20, 0.20, 0.20, 0.20, 0.20, 0.20])
    sponsor_arpu_month: list[int] = field(default_factory=lambda: [199, 229, 260, 290, 320, 360, 400, 430, 455, 475])
    # A matching product is worth nothing without athletes to match. Below this
    # pool size, paid conversion scales down with supply, otherwise the model
    # books SaaS revenue against an empty directory.
    athletes_for_full_saas_value: int = 2_000

    # ---- take rates --------------------------------------------------------
    # The corridor, now that both ends are real numbers rather than one:
    # OnlyFans 20% above (derived from Fenix International's filed accounts,
    # 1.41bn / 7.22bn = 19.5%) and Patreon 10% below -- published, and all-in,
    # including payment processing. This sat at "vs OnlyFans 20% -- deliberately
    # athlete-friendly", which was true and was only the ceiling. 01 carries
    # what each end of the corridor costs.
    take_fan: float = 0.15

    # VAT on fan subscriptions, and the reason it belongs in the model rather
    # than in a footnote.
    #
    # Art 9a of the VAT Implementing Regulation presumes a platform supplying
    # electronic services acts in its own name, and the presumption is
    # *irrebuttable* where the platform both sets the essential terms and
    # processes the payment. Stride publishes fixed take rates and runs the PSP,
    # so it does both. On that reading Stride is the deemed supplier to the fan
    # and VAT is due on the whole subscription, not on the commission.
    #
    # EU consumer prices are displayed inclusive of VAT, so the tier price a fan
    # sees is what they pay: the taxable base is that price divided by
    # (1 + rate), and the take applies to the base. Leaving this out treated
    # every fan price as if it were net, which overstated fan revenue by the
    # whole of the VAT.
    #
    # 0.21 is Spain's standard rate, and Spain is the launch market. It is a
    # simplification: B2C digital services are taxed where the *customer* is, so
    # the effective rate across the plan's markets runs roughly 20% (France, UK)
    # to 25% (Sweden, Denmark), with Portugal 23% and Italy 22%. A single
    # Spanish rate is the right base case for the early years and slightly
    # optimistic later, as the mix moves north.
    #
    # Sponsorship is deliberately untouched. Those are B2B supplies -- reverse
    # charge cross-border, and reclaimable by the buyer domestically -- so VAT
    # does not reduce what the business keeps.
    vat_rate_fan: float = 0.21
    take_sponsorship: float = 0.10
    #: Commission by sponsor plan. Free and Starter pay the headline rate; the
    #: two paid tiers pay less, because a sponsor on EUR 999 a month is already
    #: paying for the relationship. This is a pricing decision, not an estimate.
    take_sponsorship_pro: float = 0.07
    take_sponsorship_agency: float = 0.05
    #: How much more deal volume a subscribing sponsor runs than the average
    #: one. Subscribers buy campaign capacity (Pro five, Agency unlimited,
    #: free one), so their share of GMV exceeds their share of headcount. The
    #: only genuine estimate in the tiering, and deliberately low against a
    #: fivefold difference in campaign allowance.
    subscriber_volume_multiple: float = 2.0

    # ---- payment rails (charged on GMV, not on our net revenue) ------------
    # Blended card rate for a SPANISH entity, not the US headline. Stripe EEA
    # domestic is 1.5% + EUR 0.25; UK cards 2.5%; non-EEA 3.25%. Assuming a
    # mostly-European fan base with some international tail, 1.9% is the blend.
    # An earlier version of this model used the US 2.9% and overstated the
    # largest cost line in the business by roughly a third.
    psp_pct: float = 0.019
    psp_fixed_eur: float = 0.25
    payout_pct: float = 0.0025
    payout_fixed_eur: float = 0.25
    avg_fan_txn_eur: float = 9.20   # drives how badly the fixed fee bites
    avg_deal_txn_eur: float = 1_800

    # ---- infrastructure (AWS) ---------------------------------------------
    #: Rescaled with the fan base it serves, which is what drives it.
    aws_base_month: list[int] = field(default_factory=lambda: [150, 420, 1_000, 2_000, 3_200, 4_300, 5_300, 6_200, 7_000, 7_800])
    # media egress is the cost that separates a content platform from an
    # analytics one. GB per paying fan per month.
    gb_per_fan_month: float = 1.8
    egress_eur_per_gb: float = 0.008   # object storage w/ zero-egress CDN (see 02)
    egress_eur_per_gb_naive: float = 0.075  # CloudFront list: the trap

    # ---- other cost of sales ----------------------------------------------
    moderation_eur_per_1k_items: float = 22.0
    items_per_athlete_month: float = 12.0

    # ---- admission (the gate: business-plan/11-admission-and-matching.md) --
    # Applicants are not athletes. The gate admits a share of them and sends a
    # share to a human, and neither cost existed before admission was built.
    # Note what is NOT changed here: segment `cac_eur` stays as it is, because
    # it was always defined as the cost of landing one athlete ON the platform
    # (see research_data.py). Multiplying it by the funnel would double-count
    # the same money. What is genuinely new is the review labour, which is paid
    # per APPLICATION rather than per athlete.
    #
    # The direct rates are not hand-set: they are the ops-load output of
    # scripts/admission_stress.py under its modelled applicant mix. Retune a
    # threshold in the policy and these move with it.
    admission_rate_direct: float = 0.20
    review_rate_direct: float = 0.25
    # A verified club's nomination lifts an applicant's credibility floor, so
    # more clear on the first pass and fewer need a look. ESTIMATE: no intake
    # data exists; the first federation partnership is what measures it.
    admission_rate_club: float = 0.45
    review_rate_club: float = 0.18
    club_sourced_share: list[float] = field(default_factory=lambda: [0.00, 0.10, 0.20, 0.28, 0.34, 0.38, 0.42, 0.44, 0.46, 0.47])
    review_minutes: float = 4.0
    # Reviewer time is priced off the same loaded salary line the rest of the
    # model uses, rather than a second hand-set wage that could drift from it.
    ops_hours_per_year: int = 1_700

    # ---- operating costs ---------------------------------------------------
    # Hiring follows the athletes, and this is the line that decides whether
    # slowing down is prudent or merely expensive. Held at the old curve against
    # the slower ramp, the plan hired for growth that never arrived and the
    # capital requirement went from EUR 824k to EUR 3.1M -- the same company,
    # four times the money, because the costs kept the old plan's shape.
    #: Deliberately later than the first version of this plan, which ramped
    #: to 22 FTE by Y7 and needed EUR 600k to do it. Payroll is the cost
    #: that lands earliest and scales least with revenue, so moving the
    #: ramp out is what takes the raise down without building less.
    #: Lean through Y4 because that is where the cash trough sits, then a
    #: real ramp. Y1 and Y2 are the founder alone: the EUR 400k ask
    #: depends on it, since the trough is set by Y1 to Y4 spending and
    #: nothing hired after it moves the number.
    #:
    #: Y10 of 16 FTE is deliberately close to Sponsoo's 13, which is the
    #: scale this plan is now built for. The resulting revenue per
    #: employee, EUR 301k in Y7, is above the top quartile private SaaS
    #: benchmark of EUR 215k and is defended in section 3.2.2 rather than
    #: left implicit: the fan side is self serve, and content moderation
    #: is a variable cost line rather than headcount.
    headcount: list[float] = field(default_factory=lambda: [1.0, 1.0, 1.5, 2.0, 4.0, 7.0, 10.0, 12.5, 14.5, 16.0])
    loaded_salary_eur: list[int] = field(default_factory=lambda: [38_000, 52_000, 60_000, 64_000, 66_000, 68_000, 70_000, 72_000, 74_000, 76_000])
    sponsor_cac_eur: list[int] = field(default_factory=lambda: [900, 1_050, 1_200, 1_400, 1_600, 1_750, 1_900, 2_000, 2_100, 2_200])
    legal_compliance_eur: list[int] = field(default_factory=lambda: [18_000, 45_000, 90_000, 150_000, 200_000, 235_000, 270_000, 300_000, 325_000, 345_000])
    other_opex_pct_of_revenue: float = 0.08

    # ---- working capital, capex, amortisation ------------------------------
    # These existed on the workbook's WorkingCap sheet and nowhere in Python,
    # so the two disagreed about what free cash flow even means: the workbook
    # ran net profit through working capital and capex, while this model
    # returned EBITDA less tax and called it FCF. The DCF the plan quotes came
    # from the Python side, so it was discounting a cash flow the three
    # statements never produced.
    ar_days: int = 45              # sponsor receivables
    float_days: int = 15           # fan GMV held before athletes are paid, a cash benefit
    ap_days: int = 30              # trade payables
    capex_pct: float = 0.30        # share of people cost capitalised as development
    amort_years: int = 3

    # ---- financing / valuation --------------------------------------------
    # Spanish Startup Law: 15% for the first four PROFITABLE years, then the
    # standard 25%, against losses carried forward. The single flat rate this
    # replaced undercharged every year from the fifth profitable one onward.
    tax_low: float = 0.15
    tax_high: float = 0.25
    tax_low_years: int = 4
    #: The discount rate, decomposed. Two published components and one
    #: judgement, so a reader can see which is which rather than being handed
    #: a round number. See `wacc` below, which is their sum.
    #:
    #: Damodaran, NYU Stern, Cost of Capital by Industry (Europe), 5 Jan 2026:
    #: Software (Internet) at 6.01% in euros across 23 listed firms.
    wacc_mature_base: float = 0.0601
    #: Damodaran, country risk premiums, 5 Jan 2026. The sector figure above is
    #: pan-European; the company is Spanish.
    wacc_country_premium: float = 0.0155
    #: NOT SOURCED. A pre-revenue company with one product, no operating
    #: history and no liquid market in its shares does not finance itself at a
    #: listed company's cost of capital. Convention puts early-stage venture at
    #: 20-35% all-in and this sits mid-range. It is the largest single
    #: judgement in the valuation, which is why it is a line of its own.
    wacc_stage_premium: float = 0.1744
    terminal_growth: float = 0.03
    risk_free: float = 0.032       # Spanish 10Y, mid-2026
    founder_alt_return: float = 0.07



    @property
    def wacc(self) -> float:
        """The discount rate, as the sum of its parts.

        A property rather than a field so that the three components and the
        rate cannot disagree: there is no cell to leave stale.
        """
        return (self.wacc_mature_base
                + self.wacc_country_premium
                + self.wacc_stage_premium)

    @wacc.setter
    def wacc(self, value: float) -> None:
        """Move the rate by moving the judgement, which is what a sensitivity
        grid is actually asking about.

        The mature base and the country premium are published facts about the
        market; they do not flex because someone wants to see a different
        number. The stage premium is the assertion, so it absorbs the change
        and the decomposition stays true at every point on the grid.
        """
        self.wacc_stage_premium = (value - self.wacc_mature_base
                                   - self.wacc_country_premium)


#: Sponsor plan list prices, in euros per month. Named here because the tier
#: mix is derived from them and the plan quotes them in three places.
SCOUT_STARTER, SCOUT_PRO, SCOUT_AGENCY = 99, 249, 999

A = Assumptions()


# ---- the raise schedule ---------------------------------------------------
# This lived in three places -- the workbook builder, the chart data and the
# prose -- and they disagreed. The workbook was still raising EUR 400k in
# Y1/Y3/Y5 after every document had moved to EUR 600k in Y1/Y4/Y6, because
# regenerating it from this model never touched a list hardcoded in the
# builder. Years are when the gate is met, not when the money is convenient.
ROUNDS: list[dict] = [
    # Staged deliberately. The cumulative cash need is only EUR 72k to the end
    # of Y1, and Y1 is the year that settles whether fans pay at all. Raising
    # the whole runway against that question prices it as a promise; raising
    # the first tranche against it and the second against three months of real
    # subscription revenue prices the second on evidence.
    #: Priced against the comparable rather than the ambition: PitchBook puts
    #: Sponsoo's 2016 seed at a EUR 1.55M pre-money, and Spanish pre-seed
    #: rounds of this size sit between EUR 1M and EUR 3M.
    #:
    #: Gated on the rail working and sponsorship deals processing real money,
    #: not on fan churn. Fan monetisation is B2 and earns from Y2, so churn
    #: evidence cannot exist before the money that funds building it.
    {"year": 1, "stage": "Pre-seed", "amount": 150_000, "pre": 1_800_000},
    #: Roughly double, against three months of real subscription revenue. A
    #: step-up, not a re-rating. This is now the tranche that waits for the
    #: answer to the question the whole plan turns on.
    {"year": 2, "stage": "Pre-seed extension", "amount": 250_000, "pre": 3_500_000},
    # One optional growth round, replacing the EUR 2M seed and EUR 8M Series A
    # the plan carried until 1 Oct 2026. Those priced a company reaching EUR
    # 23.9M of revenue; this one reaches EUR 5.25M, and a EUR 40M pre-money
    # against that is not an aggressive assumption but a different company.
    #
    # Priced BELOW the nearest comparable rather than at it. PitchBook
    # estimates Sponsoo's Series A pre-money at EUR 15.9M, for a seven year old
    # company in the January 2021 market; EUR 12M is 5.7x our Y6 revenue of
    # EUR 2.12M and under that estimate. Pricing beneath a bubble-era mark for
    # a company further along is the conservative side of the comparable, which
    # is where a first time founder with no exit history belongs.
    #
    # Optional in the real sense: EBITDA turns positive in Y5 and cumulative
    # cash in Y6 without it. It buys speed, not survival.
    {"year": 6, "stage": "Growth (optional)", "amount": 1_500_000, "pre": 12_000_000},
]

#: The monthly recurring revenue each later round is gated on. These existed
#: only as prose in the funding table, which meant the multiple quoted in 04
#: was computed from numbers nobody could change in one place: moving a gate in
#: the document would have left the multiple beside it silently stale.
ROUND_GATE_MRR: dict[str, int] = {
    # Y6 MRR is EUR 177k on plan, so the gate is met inside the year rather
    # than at its start. Deliberately set below plan: a gate that only the plan
    # itself clears is not a gate.
    "Growth (optional)": 150_000,
}


# The two grants that dilute alongside the rounds: an advisory grant made at
# the pre-seed, and the option pool topped up to 10% at the growth round, which
# is the point at which the company takes institutional money and has employees
# worth retaining. With no Series A in the plan, grant_years() reaches its
# fallback, and the fallback is the intended answer here rather than an
# accident: the last round is the growth round.
ADVISORY_GRANT: float = 0.02
ESOP_POOL: float = 0.10


def grant_years() -> tuple[int, int]:
    """The years the advisory grant and the ESOP land in.

    Found by stage and by latest year rather than by position in ROUNDS. The
    workbook builds its own per-year grant rows and was indexing ROUNDS[0] and
    ROUNDS[-1]: reordering the list, or adding a round out of order, would have
    put the 2% grant on a different round from the one charged here, and the
    sheet would have disagreed with this module without saying so.
    """
    advisory_year = next(rd["year"] for rd in ROUNDS if rd["stage"] == "Pre-seed")
    # By stage, not by latest year: a round added after the Series A would
    # otherwise carry the option pool with it, and the plan ties the 10% to the
    # Series A milestone specifically. Falls back to the last round only if
    # there is no Series A to tie it to.
    esop_year = next((rd["year"] for rd in ROUNDS if rd["stage"] == "Series A"),
                     max(rd["year"] for rd in ROUNDS))
    return advisory_year, esop_year


def dilution() -> list[dict]:
    """The cap table after each round.

    The table in section 04 was typed by hand and did not survive its own
    arithmetic: the later rows did not follow from the earlier ones under any
    reading of the earlier ones. Deriving it here lets the doc guard pin every
    cell, which is the only thing that keeps a table like this honest.
    """
    _, esop_year = grant_years()
    out: list[dict] = []
    held = 1.0
    for rd in sorted(ROUNDS, key=lambda r: r["year"]):
        post = rd["pre"] + rd["amount"]
        stake = rd["amount"] / post
        held *= 1 - stake
        if rd["stage"] == "Pre-seed":
            held -= ADVISORY_GRANT
        out.append({**rd, "post": post, "stake": stake, "held": held})
    out.append({"year": esop_year, "stage": "ESOP (cumulative)",
                "amount": 0.0, "pre": 0.0, "post": 0.0,
                "stake": ESOP_POOL, "held": held * (1 - ESOP_POOL)})
    return out


def i(n: int) -> int:
    """Year number (1-10) -> list index."""
    return n - 1


# ─────────────────────────────────────────────────────────────────────────────
# Model
# ─────────────────────────────────────────────────────────────────────────────

def fan_path(start: float, target_end: float, churn: float,
              max_monthly_adds: float = float("inf")) -> dict:
    """Twelve months of cohort decay, solved for the gross adds that land on the
    target year-end count.

        fans[t+1] = fans[t] * (1 - churn) + adds

    so after 12 months, with r = 1 - churn:

        end = start * r^12 + adds * (1 - r^12) / (1 - r)

    Two things fall out of this that a net-stock model cannot see:

    1.  **Revenue accrues on the AVERAGE fan count, not the year-end count.**
        Charging twelve months at the December number overstates revenue by
        roughly a third during fast growth. The previous version did exactly
        that.
    2.  **Gross adds are far larger than net adds.** At 9%/month, a cohort
        retains 0.91^12 = 32% over a year, so most of next year's fans are
        replacements for this year's. That is the real acquisition load, and it
        is invisible until churn is modelled explicitly.
    """
    r = 1.0 - churn
    stock_survivors = start * r ** 12
    denom = (1 - r ** 12) / (1 - r) if churn > 0 else 12.0
    required = max(0.0, (target_end - stock_survivors) / denom)
    # Capacity binds before the target does when churn is high.
    monthly_adds = min(required, max_monthly_adds)

    fans, total, churned = start, 0.0, 0.0
    for _ in range(12):
        churned += fans * churn
        fans = fans * r + monthly_adds
        total += fans
    return {
        "avg": total / 12, "end": fans,
        "gross_adds": monthly_adds * 12, "churned": churned,
        "retained_share": (stock_survivors / start) if start else 0.0,
        "capacity_bound": monthly_adds < required - 1e-9,
        "shortfall": max(0.0, target_end - fans),
    }


def segment_year(seg: Segment, athlete_count: float, prev_athletes: float,
                 prev_fans: float, i_: int) -> dict:
    """One segment's contribution in one year, with cohort churn on both sides."""
    monetising = athlete_count * seg.monetise_rate[i_]
    target_fans = monetising * seg.fans_per_athlete[i_]
    cap_monthly = monetising * seg.max_fan_adds_per_athlete_year[i_] / 12
    fans = fan_path(prev_fans, target_fans, seg.fan_churn_month[i_], cap_monthly)

    # Revenue on the AVERAGE fan count: the honest basis.
    #
    # `fan_arpu_month` is the price a fan pays, which in the EU is displayed
    # inclusive of VAT. The taxable base is net of it; see `vat_rate_fan`.
    net_arpu = seg.fan_arpu_month[i_] / (1 + A.vat_rate_fan)
    sub_gmv = fans["avg"] * net_arpu * 12
    fan_gmv = sub_gmv * (1 + A.ppv_tips_multiple)

    deals = athlete_count * seg.deal_rate[i_] * seg.deals_per_athlete[i_]
    sponsorship_gmv = deals * seg.avg_deal_eur[i_]

    # Athletes churn too, so acquisition must replace them before it grows the
    # base. Gross adds, not net, are what marketing actually pays for.
    churn_a = seg.athlete_churn_year[i_]
    athlete_gross_adds = max(0.0, athlete_count - prev_athletes * (1 - churn_a))
    athletes_lost = prev_athletes * churn_a

    return dict(
        name=seg.name, athletes=athlete_count, paying_fans=fans["end"],
        avg_fans=fans["avg"], fan_gross_adds=fans["gross_adds"],
        fans_churned=fans["churned"], fan_retained_share=fans["retained_share"],
        capacity_bound=fans["capacity_bound"], fan_shortfall=fans["shortfall"],
        athlete_gross_adds=athlete_gross_adds, athletes_lost=athletes_lost,
        deals=deals, fan_gmv=fan_gmv, sponsorship_gmv=sponsorship_gmv,
        # Tiered, like the consolidated line. A flat rate here was not
        # harmless: render() publishes this field in the per-segment revenue
        # table, so the breakdown disagreed with the total it sums to.
        revenue=fan_gmv * A.take_fan + sponsorship_gmv * effective_take(i_),
    )


def split(i_: int) -> dict[str, float]:
    """Athletes per segment in a given year."""
    total = A.athletes[i_]
    n = total * A.niche_share[i_]
    return {"niche": n, "popular": total - n}



def tier_mix(i: int) -> dict[str, float]:
    """Share of paying subscribers on each plan, read from blended ARPU.

    A blended figure against three known list prices determines the mix without
    a separate assumption. Below the Pro price the balance is Starter; above
    it, Agency.
    """
    arpu = A.sponsor_arpu_month[i]
    if arpu < SCOUT_PRO:
        starter = (SCOUT_PRO - arpu) / (SCOUT_PRO - SCOUT_STARTER)
        return {"starter": starter, "pro": 1 - starter, "agency": 0.0}
    agency = (arpu - SCOUT_PRO) / (SCOUT_AGENCY - SCOUT_PRO)
    return {"starter": 0.0, "pro": 1 - agency, "agency": agency}


def effective_take(i: int) -> float:
    """The blended commission rate once the tiers are applied.

    Subscribers are `sponsor_paid_rate` of sponsors by headcount and
    `subscriber_volume_multiple` times that by deal volume, capped at all of
    it. Starter pays the headline rate, so only Pro and Agency reduce the
    blend.
    """
    volume_share = min(1.0, A.sponsor_paid_rate[i] * A.subscriber_volume_multiple)
    mix = tier_mix(i)
    subscriber_rate = (mix["starter"] * A.take_sponsorship
                       + mix["pro"] * A.take_sponsorship_pro
                       + mix["agency"] * A.take_sponsorship_agency)
    return (1 - volume_share) * A.take_sponsorship + volume_share * subscriber_rate


def build() -> list[dict]:
    rows = []
    prev_fans = {s.name: 0.0 for s in A.segments}
    prev_nwc = 0.0
    losses_cf = 0.0
    profitable_years = 0
    capex_history: list[float] = []
    for y in YEARS:
        i_ = i(y)
        athletes = A.athletes[i_]
        counts = split(i_)
        prev_counts = split(i_ - 1) if y > 1 else {s.name: 0.0 for s in A.segments}
        segs = [segment_year(s, counts[s.name], prev_counts[s.name],
                             prev_fans[s.name], i_) for s in A.segments]
        prev_fans = {s["name"]: s["paying_fans"] for s in segs}

        paying_fans = sum(s["paying_fans"] for s in segs)
        avg_fans = sum(s["avg_fans"] for s in segs)
        deals = sum(s["deals"] for s in segs)
        fan_gmv = sum(s["fan_gmv"] for s in segs)
        sponsorship_gmv = sum(s["sponsorship_gmv"] for s in segs)
        gmv = fan_gmv + sponsorship_gmv

        # --- net revenue ------------------------------------------------
        rev_fan = fan_gmv * A.take_fan
        rev_sponsorship = sponsorship_gmv * effective_take(i_)
        supply_factor = min(1.0, athletes / A.athletes_for_full_saas_value)
        paying_sponsors = A.sponsors[i_] * A.sponsor_paid_rate[i_] * supply_factor
        rev_saas = paying_sponsors * A.sponsor_arpu_month[i_] * 12
        revenue = rev_fan + rev_sponsorship + rev_saas

        # --- cost of sales ---------------------------------------------
        #
        # On the GROSS fan value, not the taxable base. `fan_gmv` is net of VAT
        # because that is what the take applies to, but the payment processor
        # debits the card for the whole price including VAT and charges its
        # percentage on that. Netting it here understated payments -- the
        # dominant COGS line -- by the VAT on its own fee base.
        #
        # `avg_fan_txn_eur` is a price a fan pays, so the transaction count
        # divides the gross too. Dividing net by gross undercounted the
        # transactions the fixed fee is charged per.
        fan_gross = fan_gmv * (1 + A.vat_rate_fan)
        processed = fan_gross + sponsorship_gmv
        fan_txns = fan_gross / A.avg_fan_txn_eur
        deal_txns = sponsorship_gmv / A.avg_deal_txn_eur
        psp = (processed * A.psp_pct) + (fan_txns + deal_txns) * A.psp_fixed_eur
        payouts = (processed * A.payout_pct) + (fan_txns / 30 + deal_txns) * A.payout_fixed_eur

        # On AVERAGE fans, not the year-end count. A fan uses
        # `gb_per_fan_month` for each month they are actually subscribed, so
        # twelve months times the December count bills everyone acquired during
        # the year as though they had been there since January. This is the
        # same error fan_path() documents on the revenue side -- fixed there,
        # left standing here, and it overstated infrastructure every year of
        # the plan.
        egress_gb = avg_fans * A.gb_per_fan_month * 12
        infra = A.aws_base_month[i_] * 12 + egress_gb * A.egress_eur_per_gb
        infra_naive = A.aws_base_month[i_] * 12 + egress_gb * A.egress_eur_per_gb_naive

        items = athletes * A.items_per_athlete_month * 12
        moderation = items / 1000 * A.moderation_eur_per_1k_items

        # --- admission: applications behind each athlete, and the review bill -
        # Sits in cost of sales beside moderation on purpose. The two are the
        # same obligation on opposite sides of the marketplace, vetting who is
        # on it, and vetting what they post, so splitting them across the
        # gross-margin line would be arbitrary.
        club_share = A.club_sourced_share[i_]
        athlete_gross_adds = sum(s_["athlete_gross_adds"] for s_ in segs)
        marketing_athletes = sum(s_["athlete_gross_adds"] * seg.cac_eur[i_]
                                 for seg, s_ in zip(A.segments, segs))
        admit_rate = (club_share * A.admission_rate_club
                      + (1 - club_share) * A.admission_rate_direct)
        review_rate = (club_share * A.review_rate_club
                       + (1 - club_share) * A.review_rate_direct)
        applications = athlete_gross_adds / admit_rate if admit_rate else 0.0
        reviews = applications * review_rate
        review_hourly = A.loaded_salary_eur[i_] / A.ops_hours_per_year
        verification = reviews * (A.review_minutes / 60) * review_hourly
        review_fte = reviews * (A.review_minutes / 60) / A.ops_hours_per_year
        # Memo, not a cost: segment CAC is priced per athlete ADMITTED, so this
        # is what the same money works out to per application. It is the figure
        # to hold against what a channel actually charges, if a federation
        # mailing costs more per name than this, the CAC line is understated.
        cac_per_application = (marketing_athletes / applications) if applications else 0.0

        cogs = psp + payouts + infra + moderation + verification
        gross = revenue - cogs

        # --- opex -------------------------------------------------------
        people = A.headcount[i_] * A.loaded_salary_eur[i_]
        # CAC is per segment: displacing an agent costs more than reaching an
        # athlete who has no representation at all.
        # GROSS adds, not net: churned athletes must be replaced before the base
        # grows at all, and that replacement is paid for at full CAC.
        by_name = {s["name"]: s for s in segs}
        marketing = sum(by_name[s.name]["athlete_gross_adds"] * s.cac_eur[i_] for s in A.segments)
        new_sponsors = A.sponsors[i_] - (A.sponsors[i_ - 1] if y > 1 else 0)
        marketing += max(new_sponsors, 0) * A.sponsor_cac_eur[i_]
        legal = A.legal_compliance_eur[i_]
        other = revenue * A.other_opex_pct_of_revenue
        opex = people + marketing + legal + other

        ebitda = gross - opex

        # --- working capital, capex and amortisation ----------------------
        receivables = (rev_sponsorship + rev_saas) * A.ar_days / 365
        # Gross for the same reason as the fees: the cash held before it is
        # paid out is what the fans were charged, VAT included, and the VAT
        # is held too until it is remitted.
        payout_float = processed * A.float_days / 365
        payables = opex * A.ap_days / 365
        nwc = receivables - payout_float - payables
        change_in_nwc = nwc - prev_nwc
        capex = people * A.capex_pct
        capex_history.append(capex)
        # three-year straight line on trailing capex, matching the workbook's
        # OFFSET window exactly rather than approximately
        amortisation = sum(capex_history[max(0, i_ - A.amort_years + 1):i_ + 1]) / A.amort_years
        ebit = ebitda - amortisation

        # --- tax: loss carry-forward, then the startup-rate step ----------
        losses_bf = min(0.0, losses_cf)
        taxable = max(0.0, ebit + losses_bf)
        losses_cf = min(0.0, ebit + losses_bf)
        if taxable > 0:
            profitable_years += 1
            rate = A.tax_low if profitable_years <= A.tax_low_years else A.tax_high
        else:
            rate = 0.0
        tax = taxable * rate
        net_profit = ebit - tax

        operating_cf = net_profit + amortisation - change_in_nwc
        fcf = operating_cf - capex
        prev_nwc = nwc

        rows.append(dict(
            year=y, athletes=athletes, paying_fans=paying_fans, deals=deals,
            paying_sponsors=paying_sponsors, gmv=gmv, fan_gmv=fan_gmv,
            sponsorship_gmv=sponsorship_gmv, rev_fan=rev_fan,
            rev_sponsorship=rev_sponsorship, rev_saas=rev_saas, revenue=revenue,
            psp=psp, payouts=payouts, infra=infra, infra_naive=infra_naive,
            moderation=moderation, verification=verification,
            applications=applications, reviews=reviews, admit_rate=admit_rate,
            review_fte=review_fte, cac_per_application=cac_per_application,
            review_rate=review_rate, review_hourly=review_hourly,
            cogs=cogs, gross=gross, people=people,
            marketing=marketing, legal=legal, other=other, opex=opex,
            ebitda=ebitda, amortisation=amortisation, ebit=ebit,
            taxable=taxable, tax_rate=rate, tax=tax, net_profit=net_profit,
            receivables=receivables, payout_float=payout_float, payables=payables,
            nwc=nwc, change_in_nwc=change_in_nwc, capex=capex,
            operating_cf=operating_cf, fcf=fcf,
            headcount=A.headcount[i_],
            segs={s["name"]: s for s in segs},
            niche_share=A.niche_share[i_],
            avg_fans=avg_fans,
            fan_gross_adds=sum(s["fan_gross_adds"] for s in segs),
            fans_churned=sum(s["fans_churned"] for s in segs),
            athlete_gross_adds=sum(s["athlete_gross_adds"] for s in segs),
            athletes_lost=sum(s["athletes_lost"] for s in segs),
        ))
    return rows


# The exit multiples, in one place. They were a literal inside render() and a
# reconstruction inside the doc guard, which meant changing one here would leave
# the guard happily approving the old prose -- the exact two-sources-of-truth
# failure the rest of this module exists to avoid.
EXIT_MULTIPLES: list[tuple[str, str, float, str]] = [
    ("Marketplace comparables", "4.0x revenue", 4.0, "revenue"),
    ("Blended marketplace + SaaS", "6.5x revenue", 6.5, "revenue"),
    ("High-growth SaaS mix", "9.0x revenue", 9.0, "revenue"),
    ("EBITDA multiple", "14x EBITDA", 14.0, "ebitda"),
]


def exit_values(rows: list[dict]) -> list[dict]:
    """Each exit multiple at the horizon year, and discounted back to today."""
    last = rows[-1]
    df = (1 + A.wacc) ** last["year"]          # end-of-horizon money to today
    return [{"label": label, "basis": basis,
             "at_exit": (at := max(last[key], 0.0) * mult), "today": at / df}
            for label, basis, mult, key in EXIT_MULTIPLES]


def valuation(rows: list[dict]) -> dict:
    pv = sum(r["fcf"] / (1 + A.wacc) ** r["year"] for r in rows)
    tv = rows[-1]["fcf"] * (1 + A.terminal_growth) / (A.wacc - A.terminal_growth)
    pv_tv = tv / (1 + A.wacc) ** rows[-1]["year"]
    ev = pv + pv_tv
    return dict(pv_explicit=pv, terminal_value=tv, pv_terminal=pv_tv, enterprise_value=ev)


# ─────────────────────────────────────────────────────────────────────────────
# Rendering
# ─────────────────────────────────────────────────────────────────────────────

def eur(x: float, dp: int = 0) -> str:
    if abs(x) >= 1_000_000:
        return f"€{x/1_000_000:,.2f}M"
    if abs(x) >= 1_000:
        return f"€{x/1_000:,.0f}k"
    return f"€{x:,.{dp}f}"


def num(x: float) -> str:
    return f"{x:,.0f}"


def table(head: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(head) + " |",
           "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)



# ── sensitivity ─────────────────────────────────────────────────────────────
#: Multipliers applied to the drivers the plan names as its own central
#: uncertainties. The pessimistic case also removes the niche-churn advantage
#: entirely: the plan assumes niche fans churn 45% slower than the Patreon
#: benchmark, and `benchmark_churn` divides that advantage back out rather than
#: guessing a worse number.
SCENARIOS: dict[str, dict] = {
    "Pessimistic": {
        "fans_per_athlete": 0.70,
        "monetise_rate": 0.75,
        "benchmark_churn": True,
    },
    "Optimistic": {
        "fans_per_athlete": 1.25,
        "monetise_rate": 1.20,
        "benchmark_churn": False,
    },
}

#: The advantage the base case claims over benchmark churn, stated once so the
#: prose and the scenario cannot disagree about it.
NICHE_CHURN_ADVANTAGE = 0.45

#: What the plan raises above the cash trough. It was a bare 0.4 inside
#: render(), which meant a scenario computing its own capital requirement had
#: to re-guess the convention the funding table already used.
CAPITAL_BUFFER = 0.40


def scenario(name: str) -> dict:
    """Re-run the whole model under one named scenario.

    Returns the three figures the plan quotes: Y7 revenue, Y7 EBITDA, and the
    peak capital requirement, which is the deepest point of cumulative free
    cash flow rather than any single year's loss.
    """
    import copy

    global A
    spec = SCENARIOS[name] if name in SCENARIOS else {}
    alt = copy.deepcopy(A)
    for seg in alt.segments:
        if (m := spec.get("fans_per_athlete")):
            seg.fans_per_athlete = [v * m for v in seg.fans_per_athlete]
        if (m := spec.get("monetise_rate")):
            seg.monetise_rate = [min(1.0, v * m) for v in seg.monetise_rate]
        # Niche only. The 45% advantage is a claim about niche-sport fans
        # specifically -- the popular segment is already modelled at roughly
        # benchmark -- so dividing it out of both segments invented a downside
        # the plan never claimed protection from.
        if spec.get("benchmark_churn") and seg.name == "niche":
            seg.fan_churn_month = [min(0.99, v / (1 - NICHE_CHURN_ADVANTAGE))
                                   for v in seg.fan_churn_month]

    original, A = A, alt
    try:
        rows = build()
    finally:
        A = original

    cum, trough = 0.0, 0.0
    for r in rows:
        cum += r["fcf"]
        trough = min(trough, cum)
    y7 = rows[6]
    return {"scenario": name, "revenue_y7": y7["revenue"],
            "ebitda_y7": y7["ebitda"], "trough": -trough,
            # the same convention the funding table uses, so the base column of
            # the scenario table reproduces the headline ask rather than a
            # second, smaller number that means something subtly different
            "capital_need": -trough * (1 + CAPITAL_BUFFER),
            # The year EBITDA first turns positive, returned rather than
            # asserted. Appendix C claimed the pessimistic case reached
            # profitability in Y5 "the same year as the base case", which was
            # true of the old trajectory and false of this one. That claim was
            # the document's headline robustness argument and nothing watched
            # it, because it was prose about a model behaviour rather than a
            # figure taken from one.
            "first_profit_year": next((r["year"] for r in rows
                                       if r["ebitda"] > 0), 0)}


def scenario_table() -> list[dict]:
    """Base plus every named scenario, in the order the document shows them."""
    rows = build()
    cum, trough = 0.0, 0.0
    for r in rows:
        cum += r["fcf"]
        trough = min(trough, cum)
    base = {"scenario": "Base", "revenue_y7": rows[6]["revenue"],
            "ebitda_y7": rows[6]["ebitda"], "trough": -trough,
            "capital_need": -trough * (1 + CAPITAL_BUFFER),
            # Same key as scenario() returns, so a caller can read the whole
            # table without knowing which row was built by which function.
            "first_profit_year": next((r["year"] for r in rows
                                       if r["ebitda"] > 0), 0)}
    return [scenario("Pessimistic"), base, scenario("Optimistic")]

def render(rows: list[dict]) -> dict[str, str]:
    ys = [f"Y{r['year']}" for r in rows]
    _ratios = ratios(rows)

    def line(label, key, fmt=eur):
        return [label] + [fmt(r[key]) for r in rows]

    drivers = table(["Driver"] + ys, [
        line("Active athletes", "athletes", num),
        line("Paying fans", "paying_fans", num),
        line("Sponsorship deals", "deals", num),
        line("Paying sponsors (SaaS)", "paying_sponsors", num),
        line("Headcount (FTE)", "headcount", lambda v: f"{v:,.1f}"),
    ])

    gmv = table(["Marketplace volume"] + ys, [
        line("Fan GMV (subs + unlocks)", "fan_gmv"),
        line("Sponsorship GMV", "sponsorship_gmv"),
        line("**Total GMV**", "gmv"),
    ])

    revenue = table(["Net revenue"] + ys, [
        line(f"Fan take ({A.take_fan:.0%})", "rev_fan"),
        line("Sponsorship take (blended by plan)", "rev_sponsorship"),
        line("Sponsor SaaS", "rev_saas"),
        line("**Total net revenue**", "revenue"),
    ])

    # The two columns the executive summary leads with. Generated for the same
    # reason as everything else here: a headline figure typed by hand is the one
    # a reader checks, and the one that goes stale first.
    y3, y7 = rows[2], rows[6]
    summary = table(["", "Y3", "Y7"], [
        ["Net revenue", eur(y3["revenue"]), eur(y7["revenue"])],
        ["EBITDA", eur(y3["ebitda"]), eur(y7["ebitda"])],
        ["Active athletes", num(y3["athletes"]), num(y7["athletes"])],
        ["Paying fans", num(y3["paying_fans"]), num(y7["paying_fans"])],
        ["Gross margin",
         f"{100 * y3['gross'] / y3['revenue']:,.0f}%",
         f"{100 * y7['gross'] / y7['revenue']:,.0f}%"],
    ])

    pl = table(["P&L"] + ys, [
        line("Net revenue", "revenue"),
        line("Payment processing", "psp"),
        line("Payouts", "payouts"),
        line("Infrastructure (AWS)", "infra"),
        line("Moderation", "moderation"),
        line("Athlete verification", "verification"),
        line("**Gross profit**", "gross"),
        ["Gross margin"] + [f"{(r['gross']/r['revenue']*100 if r['revenue'] else 0):,.0f}%" for r in rows],
        line("People", "people"),
        line("Marketing / CAC", "marketing"),
        line("Legal & compliance", "legal"),
        line("Other opex", "other"),
        line("**EBITDA**", "ebitda"),
        line("Tax", "tax"),
        # Without these two rows the table ran EBITDA -> Tax -> Free cash flow,
        # and a reader doing the obvious subtraction got a different number in
        # every year from the fourth on (Y7: 8.6M by that arithmetic against the
        # 10.2M printed). The bridge is not decoration: working capital is a
        # *source* of cash here, and a P&L that hides it looks like an error.
        line("Working capital movement", "change_in_nwc"),
        line("Capex (capitalised development)", "capex"),
        line("**Free cash flow**", "fcf"),
    ])

    egress = table(["Egress strategy"] + ys, [
        line("AWS w/ zero-egress CDN", "infra"),
        line("AWS w/ CloudFront list price", "infra_naive"),
        ["**Annual difference**"] + [eur(r["infra_naive"] - r["infra"]) for r in rows],
    ])

    v = valuation(rows)
    val = table(["Valuation (DCF)", "Value"], [
        [f"PV of explicit FCF, Y1–Y{YEARS[-1]}", eur(v["pv_explicit"])],
        [f"Terminal value (g={A.terminal_growth:.0%})", eur(v["terminal_value"])],
        ["PV of terminal value", eur(v["pv_terminal"])],
        [f"**Enterprise value (WACC {A.wacc:.0%})**", f"**{eur(v['enterprise_value'])}**"],
    ])

    # `rows[-1]` is Y10, the end of the explicit period and the year the terminal
    # value is struck from: but all four rows here were labelled Y7, so the
    # table quoted an exit three years later than it claimed. The prose beneath
    # it always reasoned about Y10 ("the day after Y10", "EUR 58M revenue"); the
    # labels were the only part that was wrong, so the labels are what moved.
    last = rows[-1]
    df = (1 + A.wacc) ** last["year"]   # discount end-of-horizon money to today
    mult = table([f"Exit method (Y{last['year']})", "Multiple",
                  f"Value at Y{last['year']}", "Discounted to today"],
                 [[e["label"], e["basis"], eur(e["at_exit"]), eur(e["today"])]
                  for e in exit_values(rows)])

    # Cost structure at maturity. Hand-written until it drifted: the table
    # survived the Stripe rate correction unchanged and went on claiming EUR
    # 8.68M of payment processing against a model saying EUR 6.04M. Generated
    # now, ordered by size, so it restates itself whenever an input moves.
    mat = rows[6]
    mat_lines = [("Payment processing", "psp"), ("People", "people"),
                 ("Marketing / CAC", "marketing"), ("Other opex", "other"),
                 ("Payouts", "payouts"), ("Infrastructure", "infra"),
                 ("Legal & compliance", "legal"), ("Moderation", "moderation"),
                 ("Athlete verification", "verification")]
    costs_y7 = table(["Line", f"Y{mat['year']} amount", "% of revenue"],
                     [[label, eur(mat[key]), f"{mat[key] / mat['revenue']:.1%}"]
                      for label, key in sorted(mat_lines, key=lambda x: -mat[x[1]])]
                     + [["**EBITDA**", f"**{eur(mat['ebitda'])}**",
                         f"**{mat['ebitda'] / mat['revenue']:.1%}**"]])

    # Blended athlete CAC is the cost of a GROSS add, which is neither segment's
    # headline number: the mix shifts towards the expensive popular segment as
    # the plan matures, so a single hand-written pair of figures goes stale fast.
    def blended_cac(r):
        adds = r["athlete_gross_adds"]
        return (r["cac_per_application"] * r["applications"] / adds) if adds else 0.0

    cac = table(["", "Athlete", "Fan", "Sponsor"], [
        ["Y1 CAC", f"€{blended_cac(rows[0]):,.0f}", "~€0", f"€{A.sponsor_cac_eur[0]:,}"],
        ["Y7 CAC", f"€{blended_cac(rows[6]):,.0f}", "~€0", f"€{A.sponsor_cac_eur[6]:,}"],
        ["Applications behind one athlete",
         f"{1 / rows[0]['admit_rate']:.1f}x in Y1, {1 / rows[6]['admit_rate']:.1f}x in Y7",
         # Empty, not a stray colon: the em-dash sweep turned the two
         # not-applicable cells into bare punctuation.
         "", ""],
        ["Channel", "Clubs, federations, ambassador referral",
         "**Brought by the athlete**", "Outbound, events, agency partnerships"],
    ])

    # Sensitivity, generated. The hand-written version quoted a base cell that
    # did not match the base case beside it, which is the failure mode of any
    # table typed once and never recomputed.
    base_w, base_g = A.wacc, A.terminal_growth
    grid_w, grid_g = (0.20, 0.25, 0.30), (0.02, 0.03, 0.04)
    sens_rows = []
    for g in grid_g:
        cells = []
        for w in grid_w:
            A.wacc, A.terminal_growth = w, g
            ev = valuation(build())["enterprise_value"]
            cells.append(f"**{eur(ev)}**" if (w, g) == (base_w, base_g) else eur(ev))
        sens_rows.append([f"Terminal growth {g:.0%}"] + cells)
    A.wacc, A.terminal_growth = base_w, base_g
    sensitivity = table(["Enterprise value"] + [f"WACC {w:.0%}" for w in grid_w], sens_rows)

    # cumulative funding need = deepest point of cumulative FCF
    cum, trough, trough_year = 0.0, 0.0, 1
    cash_rows = []
    for r in rows:
        cum += r["fcf"]
        if cum < trough:
            trough, trough_year = cum, r["year"]
        cash_rows.append([f"Y{r['year']}", eur(r["fcf"]), eur(cum)])
    cash = table(["Year", "Free cash flow", "Cumulative"], cash_rows)

    funding = table(["Capital requirement", "Value"], [
        ["Deepest cumulative cash position", eur(trough)],
        ["Year it occurs", f"Y{trough_year}"],
        [f"Buffer at {CAPITAL_BUFFER:.0%} (hiring slips, churn worse)",
         eur(abs(trough) * CAPITAL_BUFFER)],
        ["**Total capital to fund the plan**",
         f"**{eur(abs(trough) * (1 + CAPITAL_BUFFER))}**"],
        ["First EBITDA-positive year", f"Y{next((r['year'] for r in rows if r['ebitda'] > 0), 0)}"],
    ])

    churn = table(["Retention & acquisition"] + ys, [
        line("Paying fans, year end", "paying_fans", num),
        line("Paying fans, average", "avg_fans", num),
        line("Fans acquired (gross)", "fan_gross_adds", num),
        line("Fans lost to churn", "fans_churned", num),
        line("Athletes acquired (gross)", "athlete_gross_adds", num),
        line("Athletes lost to churn", "athletes_lost", num),
    ])

    seg_rows = []
    for key, label in (("niche", "Niche (market creation)"), ("popular", "Popular (disintermediation)")):
        seg_rows.append([f"**{label}**"] + ["" for _ in rows])
        seg_rows.append(["  Athletes"] + [num(r["segs"][key]["athletes"]) for r in rows])
        seg_rows.append(["  Paying fans"] + [num(r["segs"][key]["paying_fans"]) for r in rows])
        seg_rows.append(["  Deals"] + [num(r["segs"][key]["deals"]) for r in rows])
        seg_rows.append(["  Net revenue"] + [eur(r["segs"][key]["revenue"]) for r in rows])
    seg_rows.append(["**Niche share of athletes**"] + [f"{r['niche_share']:.0%}" for r in rows])
    seg_rows.append(["**Niche share of revenue**"] + [
        f"{r['segs']['niche']['revenue'] / (r['segs']['niche']['revenue'] + r['segs']['popular']['revenue']):.0%}"
        for r in rows])
    segments = table(["Segment"] + ys, seg_rows)

    return dict(drivers=drivers, gmv=gmv, revenue=revenue, pl=pl, egress=egress,
                summary=summary, unit_economics=unit_economics(),
                valuation=val, multiples=mult, cash=cash, funding=funding,
                segments=segments, churn=churn,
                costs_y7=costs_y7, cac=cac, sensitivity=sensitivity,
                ratios=_ratios)


def unit_economics() -> str:
    """The fixed-fee problem, per transaction size.

    Prices come from `market_model`, which is where the tier design lives. This
    kept its own copy and the copy drifted: it carried a EUR 14.99 tier that
    exists in no other document, and priced the season pass at EUR 99 while
    01-revenue-model.md, the tier table and the retention guard all say EUR 89.
    """
    import market_model

    rows = []
    tiers = [(p, "") for p in market_model.TIER_PRICES]
    # The season pass is the only annual row, under a header that says monthly.
    # The hand-typed table it replaced carried the annotation; losing it made the
    # pass read as a EUR 89/month tier, directly under a paragraph arguing for
    # annual billing.
    tiers.append((market_model.SEASON_PASS_EUR, " (annual)"))
    for price, period in tiers:
        # The displayed price is VAT-inclusive, so the take is charged on the
        # base and the processor's fee on the price. Taking 15% of the shelf
        # price here overstated every row by the VAT, and this table is the
        # argument for a price floor -- the one place the arithmetic has to be
        # exactly right.
        take = (price / (1 + A.vat_rate_fan)) * A.take_fan
        psp = price * A.psp_pct + A.psp_fixed_eur
        net = take - psp
        rows.append([
            f"€{price:,.2f}{period}",
            f"€{take:,.2f}",
            f"€{psp:,.2f}",
            f"€{net:,.2f}",
            f"{(net/take*100 if take else 0):,.0f}%",
        ])
    return table(
        ["Fan pays (monthly)", f"Our take ({A.take_fan:.0%})", "Payment cost", "We keep", "% of take retained"],
        rows,
    )


DOC_TABLES = {
    "00-executive-summary.md": ["summary"],
    # The submission body carries the same block. It sat between MODEL
    # markers while being hand-maintained, which is the worst of both:
    # it looked generated and was one EBITDA cell stale.
    "esade-body.md": ["summary", "ratios"],
    "02-cost-model.md": ["costs_y7", "cac", "unit_economics"],
    "03-financial-model.md": ["drivers", "churn", "segments", "gmv", "revenue", "pl", "cash", "funding"],
    "04-capital-and-valuation.md": ["valuation", "multiples", "sensitivity"],
}


def ratios(rows: list[dict]) -> str:
    """The feasibility ratios, for outline item 9.6.

    Four columns rather than ten: a ratio table is read for its shape, and Y1
    and Y2 ratios on a near-zero revenue base are noise that crowds out the
    trend. The years shown are the ones the rest of the plan quotes.
    """
    pick = [2, 4, 6, 9]                      # Y3, Y5, Y7, Y10
    head = ["Ratio"] + [f"Y{rows[i]['year']}" for i in pick] + ["What it says"]

    def growth(i: int) -> float:
        return rows[i]["revenue"] / rows[i - 1]["revenue"] - 1

    def burn_multiple(i: int) -> float:
        """Net burn divided by net new revenue. Undefined once profitable."""
        burn = -rows[i]["fcf"] if rows[i]["fcf"] < 0 else 0.0
        net_new = rows[i]["revenue"] - rows[i - 1]["revenue"]
        return burn / net_new if burn > 0 and net_new > 0 else 0.0

    body = [
        ["Gross margin"] + [f"{rows[i]['gross'] / rows[i]['revenue']:.0%}" for i in pick]
        + ["Capped by the payment rail, not by engineering"],
        ["EBITDA margin"] + [f"{rows[i]['ebitda'] / rows[i]['revenue']:.0%}" for i in pick]
        + ["Turns positive in Y5"],
        ["Net margin"] + [f"{rows[i]['net_profit'] / rows[i]['revenue']:.0%}" for i in pick]
        + ["Below EBITDA by amortisation and tax"],
        ["Cost of sales / revenue"] + [f"{rows[i]['cogs'] / rows[i]['revenue']:.0%}" for i in pick]
        + ["Falls as fan subscriptions outgrow one-off payments"],
        ["Revenue growth"] + [f"{growth(i):.0%}" for i in pick]
        + ["Decelerating, which is the shape a marketplace should have"],
        ["Revenue per FTE"] + [eur(rows[i]["revenue"] / rows[i]["headcount"]) for i in pick]
        + ["Above the sector's top quartile; defended in 3.2.2"],
        ["**Rule of 40**"] + [f"**{(growth(i) + rows[i]['ebitda'] / rows[i]['revenue']) * 100:.0f}**"
                              for i in pick]
        + ["**Growth plus EBITDA margin. Above 40 in every year shown**"],
        ["Burn multiple"] + [(f"{burn_multiple(i):.2f}" if burn_multiple(i) else "n/a")
                             for i in pick]
        + ["Net burn per euro of new revenue. n/a once cash-generative"],
    ]
    return table(head, body)


def write_docs(rendered: dict[str, str]) -> None:
    """Replace the content between <!-- MODEL:key --> and <!-- /MODEL:key -->.

    The narrative stays hand-written and in control of what is shown; only the
    tables are generated. Three rounds of propagating numbers by hand was
    enough: a figure that appears in a document should come from the model that
    produced it.
    """
    import pathlib
    here = pathlib.Path(__file__).parent
    for filename, keys in DOC_TABLES.items():
        path = here / filename
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        for key in keys:
            start, end = f"<!-- MODEL:{key} -->", f"<!-- /MODEL:{key} -->"
            if start not in text or end not in text:
                continue
            head, _, rest = text.partition(start)
            _, _, tail = rest.partition(end)
            text = head + start + "\n" + rendered[key] + "\n" + end + tail
        path.write_text(text, encoding="utf-8")
        print(f"wrote {filename}")


def main() -> None:
    rows = build()
    r = render(rows)
    print("\n## Drivers\n\n" + r["drivers"])
    print("\n## Retention & acquisition\n\n" + r["churn"])
    print("\n## Segments\n\n" + r["segments"])
    print("\n## GMV\n\n" + r["gmv"])
    print("\n## Net revenue\n\n" + r["revenue"])
    print("\n## P&L\n\n" + r["pl"])
    print("\n## Egress strategy\n\n" + r["egress"])
    print("\n## Unit economics per subscription tier\n\n" + unit_economics())
    print("\n## Cash\n\n" + r["cash"])
    print("\n## Capital requirement\n\n" + r["funding"])
    print("\n## Valuation\n\n" + r["valuation"])
    print("\n" + r["multiples"])

    if "--write" in sys.argv:
        print()
        write_docs(r)


if __name__ == "__main__":
    main()
