"""Stride — 7-year financial model.

Every table in 03-financial-model.md and 04-capital-and-valuation.md is
generated by this script. Nothing in those documents is hand-typed, so the
arithmetic is reproducible and an examiner can change one assumption and see
the whole model move:

    python business-plan/model.py            # print all tables
    python business-plan/model.py --write    # regenerate the markdown docs

Currency is EUR throughout (the company is Spanish). Note the product currently
stores money in `*_usd` columns — see 05-product-gaps.md.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field

YEARS = list(range(1, 8))  # Y1 = 2027


# ─────────────────────────────────────────────────────────────────────────────
# Assumptions. Every number a reader might argue with lives here.
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Assumptions:
    # ---- demand side -------------------------------------------------------
    athletes: list[int] = field(default_factory=lambda: [400, 1_800, 5_500, 13_000, 25_000, 38_000, 52_000])
    # share of athletes who actually turn on fan monetisation
    monetise_rate: list[float] = field(default_factory=lambda: [0.22, 0.26, 0.30, 0.34, 0.37, 0.39, 0.40])
    # paying fans per monetising athlete (power law: most have few, a tail carries it)
    fans_per_athlete: list[int] = field(default_factory=lambda: [18, 20, 23, 26, 28, 30, 32])
    fan_arpu_month: list[float] = field(default_factory=lambda: [7.50, 7.80, 8.00, 8.20, 8.40, 8.50, 8.60])
    fan_churn_month: list[float] = field(default_factory=lambda: [0.11, 0.10, 0.09, 0.085, 0.08, 0.075, 0.07])

    # one-off fan spend (unlocks + tips) as a multiple of subscription GMV
    ppv_tips_multiple: float = 0.35

    # ---- sponsorship -------------------------------------------------------
    deal_rate: list[float] = field(default_factory=lambda: [0.08, 0.11, 0.14, 0.17, 0.19, 0.21, 0.22])
    deals_per_athlete: list[float] = field(default_factory=lambda: [1.2, 1.3, 1.5, 1.7, 1.9, 2.0, 2.2])
    avg_deal_eur: list[int] = field(default_factory=lambda: [1_200, 1_400, 1_650, 1_900, 2_100, 2_250, 2_400])

    # ---- sponsor SaaS ------------------------------------------------------
    sponsors: list[int] = field(default_factory=lambda: [25, 110, 340, 800, 1_500, 2_400, 3_500])
    sponsor_paid_rate: list[float] = field(default_factory=lambda: [0.10, 0.14, 0.17, 0.19, 0.20, 0.20, 0.20])
    sponsor_arpu_month: list[int] = field(default_factory=lambda: [199, 229, 260, 290, 320, 360, 400])

    # ---- take rates --------------------------------------------------------
    take_fan: float = 0.15        # vs OnlyFans 20% — deliberately athlete-friendly
    take_sponsorship: float = 0.10

    # ---- payment rails (charged on GMV, not on our net revenue) ------------
    psp_pct: float = 0.029
    psp_fixed_eur: float = 0.25
    payout_pct: float = 0.0025
    payout_fixed_eur: float = 0.25
    avg_fan_txn_eur: float = 9.20   # drives how badly the fixed fee bites
    avg_deal_txn_eur: float = 1_800

    # ---- infrastructure (AWS) ---------------------------------------------
    aws_base_month: list[int] = field(default_factory=lambda: [180, 650, 2_100, 5_400, 11_000, 17_000, 24_000])
    # media egress is the cost that separates a content platform from an
    # analytics one. GB per paying fan per month.
    gb_per_fan_month: float = 1.8
    egress_eur_per_gb: float = 0.008   # object storage w/ zero-egress CDN (see 02)
    egress_eur_per_gb_naive: float = 0.075  # CloudFront list — the trap

    # ---- other cost of sales ----------------------------------------------
    moderation_eur_per_1k_items: float = 22.0
    items_per_athlete_month: float = 12.0

    # ---- operating costs ---------------------------------------------------
    headcount: list[float] = field(default_factory=lambda: [1.5, 3.0, 7.0, 14.0, 24.0, 36.0, 50.0])
    loaded_salary_eur: list[int] = field(default_factory=lambda: [38_000, 52_000, 60_000, 64_000, 66_000, 68_000, 70_000])
    athlete_cac_eur: list[int] = field(default_factory=lambda: [22, 26, 30, 34, 38, 42, 45])
    sponsor_cac_eur: list[int] = field(default_factory=lambda: [900, 1_050, 1_200, 1_400, 1_600, 1_750, 1_900])
    legal_compliance_eur: list[int] = field(default_factory=lambda: [18_000, 45_000, 90_000, 150_000, 200_000, 235_000, 270_000])
    other_opex_pct_of_revenue: float = 0.08

    # ---- financing / valuation --------------------------------------------
    tax_rate: float = 0.15         # Spanish Startup Law: 15% for first 4 profitable years
    wacc: float = 0.25
    terminal_growth: float = 0.03
    risk_free: float = 0.032       # Spanish 10Y, mid-2026
    founder_alt_return: float = 0.07


A = Assumptions()


def i(n: int) -> int:
    """Year number (1-7) -> list index."""
    return n - 1


# ─────────────────────────────────────────────────────────────────────────────
# Model
# ─────────────────────────────────────────────────────────────────────────────

def build() -> list[dict]:
    rows = []
    for y in YEARS:
        i_ = i(y)
        athletes = A.athletes[i_]
        monetising = athletes * A.monetise_rate[i_]
        paying_fans = monetising * A.fans_per_athlete[i_]

        # --- GMV --------------------------------------------------------
        sub_gmv = paying_fans * A.fan_arpu_month[i_] * 12
        ppv_gmv = sub_gmv * A.ppv_tips_multiple
        fan_gmv = sub_gmv + ppv_gmv

        deal_athletes = athletes * A.deal_rate[i_]
        deals = deal_athletes * A.deals_per_athlete[i_]
        sponsorship_gmv = deals * A.avg_deal_eur[i_]

        gmv = fan_gmv + sponsorship_gmv

        # --- net revenue ------------------------------------------------
        rev_fan = fan_gmv * A.take_fan
        rev_sponsorship = sponsorship_gmv * A.take_sponsorship
        paying_sponsors = A.sponsors[i_] * A.sponsor_paid_rate[i_]
        rev_saas = paying_sponsors * A.sponsor_arpu_month[i_] * 12
        revenue = rev_fan + rev_sponsorship + rev_saas

        # --- cost of sales ---------------------------------------------
        fan_txns = fan_gmv / A.avg_fan_txn_eur
        deal_txns = sponsorship_gmv / A.avg_deal_txn_eur
        psp = (gmv * A.psp_pct) + (fan_txns + deal_txns) * A.psp_fixed_eur
        payouts = (gmv * A.payout_pct) + (fan_txns / 30 + deal_txns) * A.payout_fixed_eur

        egress_gb = paying_fans * A.gb_per_fan_month * 12
        infra = A.aws_base_month[i_] * 12 + egress_gb * A.egress_eur_per_gb
        infra_naive = A.aws_base_month[i_] * 12 + egress_gb * A.egress_eur_per_gb_naive

        items = athletes * A.items_per_athlete_month * 12
        moderation = items / 1000 * A.moderation_eur_per_1k_items

        cogs = psp + payouts + infra + moderation
        gross = revenue - cogs

        # --- opex -------------------------------------------------------
        people = A.headcount[i_] * A.loaded_salary_eur[i_]
        new_athletes = athletes - (A.athletes[i_ - 1] if y > 1 else 0)
        new_sponsors = A.sponsors[i_] - (A.sponsors[i_ - 1] if y > 1 else 0)
        marketing = max(new_athletes, 0) * A.athlete_cac_eur[i_] + max(new_sponsors, 0) * A.sponsor_cac_eur[i_]
        legal = A.legal_compliance_eur[i_]
        other = revenue * A.other_opex_pct_of_revenue
        opex = people + marketing + legal + other

        ebitda = gross - opex
        tax = max(0.0, ebitda) * A.tax_rate
        fcf = ebitda - tax

        rows.append(dict(
            year=y, athletes=athletes, paying_fans=paying_fans, deals=deals,
            paying_sponsors=paying_sponsors, gmv=gmv, fan_gmv=fan_gmv,
            sponsorship_gmv=sponsorship_gmv, rev_fan=rev_fan,
            rev_sponsorship=rev_sponsorship, rev_saas=rev_saas, revenue=revenue,
            psp=psp, payouts=payouts, infra=infra, infra_naive=infra_naive,
            moderation=moderation, cogs=cogs, gross=gross, people=people,
            marketing=marketing, legal=legal, other=other, opex=opex,
            ebitda=ebitda, tax=tax, fcf=fcf,
            headcount=A.headcount[i_],
        ))
    return rows


def valuation(rows: list[dict]) -> dict:
    pv = sum(r["fcf"] / (1 + A.wacc) ** r["year"] for r in rows)
    tv = rows[-1]["fcf"] * (1 + A.terminal_growth) / (A.wacc - A.terminal_growth)
    pv_tv = tv / (1 + A.wacc) ** rows[-1]["year"]
    ev = pv + pv_tv
    return dict(pv_explicit=pv, terminal_value=tv, pv_terminal=pv_tv, enterprise_value=ev)


# ─────────────────────────────────────────────────────────────────────────────
# Rendering
# ─────────────────────────────────────────────────────────────────────────────

def eur(x: float, dp: int = 0) -> str:
    if abs(x) >= 1_000_000:
        return f"€{x/1_000_000:,.2f}M"
    if abs(x) >= 1_000:
        return f"€{x/1_000:,.0f}k"
    return f"€{x:,.{dp}f}"


def num(x: float) -> str:
    return f"{x:,.0f}"


def table(head: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(head) + " |",
           "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def render(rows: list[dict]) -> dict[str, str]:
    ys = [f"Y{r['year']}" for r in rows]

    def line(label, key, fmt=eur):
        return [label] + [fmt(r[key]) for r in rows]

    drivers = table(["Driver"] + ys, [
        line("Active athletes", "athletes", num),
        line("Paying fans", "paying_fans", num),
        line("Sponsorship deals", "deals", num),
        line("Paying sponsors (SaaS)", "paying_sponsors", num),
        line("Headcount (FTE)", "headcount", lambda v: f"{v:,.1f}"),
    ])

    gmv = table(["Marketplace volume"] + ys, [
        line("Fan GMV (subs + unlocks)", "fan_gmv"),
        line("Sponsorship GMV", "sponsorship_gmv"),
        line("**Total GMV**", "gmv"),
    ])

    revenue = table(["Net revenue"] + ys, [
        line(f"Fan take ({A.take_fan:.0%})", "rev_fan"),
        line(f"Sponsorship take ({A.take_sponsorship:.0%})", "rev_sponsorship"),
        line("Sponsor SaaS", "rev_saas"),
        line("**Total net revenue**", "revenue"),
    ])

    pl = table(["P&L"] + ys, [
        line("Net revenue", "revenue"),
        line("Payment processing", "psp"),
        line("Payouts", "payouts"),
        line("Infrastructure (AWS)", "infra"),
        line("Moderation", "moderation"),
        line("**Gross profit**", "gross"),
        ["Gross margin"] + [f"{(r['gross']/r['revenue']*100 if r['revenue'] else 0):,.0f}%" for r in rows],
        line("People", "people"),
        line("Marketing / CAC", "marketing"),
        line("Legal & compliance", "legal"),
        line("Other opex", "other"),
        line("**EBITDA**", "ebitda"),
        line("Tax", "tax"),
        line("**Free cash flow**", "fcf"),
    ])

    egress = table(["Egress strategy"] + ys, [
        line("AWS w/ zero-egress CDN", "infra"),
        line("AWS w/ CloudFront list price", "infra_naive"),
        ["**Annual difference**"] + [eur(r["infra_naive"] - r["infra"]) for r in rows],
    ])

    v = valuation(rows)
    val = table(["Valuation (DCF)", "Value"], [
        ["PV of explicit FCF, Y1–Y7", eur(v["pv_explicit"])],
        [f"Terminal value (g={A.terminal_growth:.0%})", eur(v["terminal_value"])],
        ["PV of terminal value", eur(v["pv_terminal"])],
        [f"**Enterprise value (WACC {A.wacc:.0%})**", f"**{eur(v['enterprise_value'])}**"],
    ])

    last = rows[-1]
    df = (1 + A.wacc) ** last["year"]   # discount Y7 money back to today
    mult = table(["Exit method (Y7)", "Multiple", "Value AT Y7", "Discounted to today"], [
        ["Marketplace comparables", "4.0x revenue", eur(last["revenue"] * 4), eur(last["revenue"] * 4 / df)],
        ["Blended marketplace + SaaS", "6.5x revenue", eur(last["revenue"] * 6.5), eur(last["revenue"] * 6.5 / df)],
        ["High-growth SaaS mix", "9.0x revenue", eur(last["revenue"] * 9), eur(last["revenue"] * 9 / df)],
        ["EBITDA multiple", "14x EBITDA", eur(max(last["ebitda"], 0) * 14), eur(max(last["ebitda"], 0) * 14 / df)],
    ])

    # cumulative funding need = deepest point of cumulative FCF
    cum, trough, trough_year = 0.0, 0.0, 1
    cash_rows = []
    for r in rows:
        cum += r["fcf"]
        if cum < trough:
            trough, trough_year = cum, r["year"]
        cash_rows.append([f"Y{r['year']}", eur(r["fcf"]), eur(cum)])
    cash = table(["Year", "Free cash flow", "Cumulative"], cash_rows)

    funding = table(["Capital requirement", "Value"], [
        ["Deepest cumulative cash position", eur(trough)],
        ["Year it occurs", f"Y{trough_year}"],
        ["Buffer at 40% (hiring slips, churn worse)", eur(abs(trough) * 0.4)],
        ["**Total capital to fund the plan**", f"**{eur(abs(trough) * 1.4)}**"],
        ["First EBITDA-positive year", f"Y{next((r['year'] for r in rows if r['ebitda'] > 0), 0)}"],
    ])

    return dict(drivers=drivers, gmv=gmv, revenue=revenue, pl=pl, egress=egress,
                valuation=val, multiples=mult, cash=cash, funding=funding)


def unit_economics() -> str:
    """The fixed-fee problem, per transaction size."""
    rows = []
    for price in (4.99, 9.99, 14.99, 24.99, 99.00):
        take = price * A.take_fan
        psp = price * A.psp_pct + A.psp_fixed_eur
        net = take - psp
        rows.append([
            f"€{price:,.2f}",
            f"€{take:,.2f}",
            f"€{psp:,.2f}",
            f"€{net:,.2f}",
            f"{(net/take*100 if take else 0):,.0f}%",
        ])
    return table(
        ["Fan pays (monthly)", f"Our take ({A.take_fan:.0%})", "Payment cost", "We keep", "% of take retained"],
        rows,
    )


def main() -> None:
    rows = build()
    r = render(rows)
    print("\n## Drivers\n\n" + r["drivers"])
    print("\n## GMV\n\n" + r["gmv"])
    print("\n## Net revenue\n\n" + r["revenue"])
    print("\n## P&L\n\n" + r["pl"])
    print("\n## Egress strategy\n\n" + r["egress"])
    print("\n## Unit economics per subscription tier\n\n" + unit_economics())
    print("\n## Cash\n\n" + r["cash"])
    print("\n## Capital requirement\n\n" + r["funding"])
    print("\n## Valuation\n\n" + r["valuation"])
    print("\n" + r["multiples"])

    if "--write" in sys.argv:
        print("\n(--write is a placeholder: tables above are pasted into the docs by hand "
              "so the narrative stays in control of what is shown.)")


if __name__ == "__main__":
    main()
