"""Stride — 10-year financial model.

Every table in 03-financial-model.md and 04-capital-and-valuation.md is
generated by this script. Nothing in those documents is hand-typed, so the
arithmetic is reproducible and an examiner can change one assumption and see
the whole model move:

    python business-plan/model.py            # print all tables
    python business-plan/model.py --write    # regenerate the markdown docs

Currency is EUR throughout (the company is Spanish). Note the product currently
stores money in `*_usd` columns — see 05-product-gaps.md.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field

YEARS = list(range(1, 11))  # Y1 = 2027 .. Y10 = 2036

# Ten years, not seven. At Y7 the company is still compounding above 50%, so a
# perpetuity-growth terminal value placed there does most of the valuation work
# and does it badly. Extending to Y10 lets growth decelerate inside the explicit
# forecast, which is where it belongs.


# ─────────────────────────────────────────────────────────────────────────────
# Assumptions. Every number a reader might argue with lives here.
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Segment:
    """One market segment. The two differ in kind, not just in size — see
    business-plan/06-market-strategy.md and sport_index.py.

    NICHE (market creation): no agent exists. Fans are usually participants in
    the same sport, so conversion is high and they pay for knowledge. Smaller
    followings, cheaper to acquire, smaller sponsorship deals.

    POPULAR (disintermediation): an agent already takes 10-20%. Larger
    followings but lower conversion — a football fan follows a club, not a
    training plan. Expensive to acquire because there is a relationship to
    displace, but the deals are much larger.
    """
    name: str
    monetise_rate: list[float]      # share of athletes who turn on fan monetisation
    fans_per_athlete: list[int]     # paying fans per monetising athlete, at YEAR END
    fan_arpu_month: list[float]
    fan_churn_month: list[float]    # monthly, compounds — see fan_path()
    athlete_churn_year: list[float]  # annual; drives gross adds, and therefore CAC
    deal_rate: list[float]          # share of athletes landing >=1 deal a year
    deals_per_athlete: list[float]
    avg_deal_eur: list[int]
    cac_eur: list[int]
    # An athlete cannot recruit unlimited new paying fans: their audience is
    # finite and they can only convert so much of it per year. Without this
    # ceiling the model treats the year-end target as reachable at ANY churn
    # rate, which makes high churn *raise* revenue — more churn simply means
    # more gross adds through the year, so average fans go up. That is
    # backwards, and this cap is what makes churn bite.
    max_fan_adds_per_athlete_year: list[int]


NICHE = Segment(
    name="niche",
    monetise_rate=[0.28, 0.32, 0.37, 0.41, 0.44, 0.46, 0.48, 0.49, 0.50, 0.50],
    fans_per_athlete=[20, 22, 25, 28, 30, 32, 34, 35, 36, 37],
    fan_arpu_month=[8.00, 8.30, 8.60, 8.80, 9.00, 9.10, 9.20, 9.30, 9.40, 9.50],
    # Niche fans churn less: they subscribed for knowledge, and training is a
    # habit rather than an impulse. Seasons also create natural renewal points.
    fan_churn_month=[0.090, 0.085, 0.080, 0.075, 0.070, 0.065, 0.060, 0.058, 0.056, 0.055],
    athlete_churn_year=[0.30, 0.27, 0.24, 0.22, 0.20, 0.19, 0.18, 0.17, 0.16, 0.16],
    deal_rate=[0.05, 0.07, 0.09, 0.11, 0.13, 0.15, 0.16, 0.17, 0.17, 0.18],
    deals_per_athlete=[1.1, 1.2, 1.3, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 2.0],
    avg_deal_eur=[900, 1_050, 1_200, 1_350, 1_500, 1_600, 1_700, 1_800, 1_900, 2_000],
    cac_eur=[16, 18, 21, 24, 27, 30, 32, 34, 35, 36],
    max_fan_adds_per_athlete_year=[30, 33, 36, 40, 43, 45, 47, 49, 50, 52],
)

POPULAR = Segment(
    name="popular",
    monetise_rate=[0.14, 0.17, 0.20, 0.23, 0.26, 0.28, 0.30, 0.31, 0.32, 0.32],
    fans_per_athlete=[26, 29, 32, 35, 38, 41, 44, 46, 47, 48],
    fan_arpu_month=[7.00, 7.20, 7.40, 7.60, 7.80, 7.90, 8.00, 8.10, 8.20, 8.30],
    # Popular-sport fans churn harder: an impulse follow after a result, with
    # many competing ways to consume the same athlete for free.
    fan_churn_month=[0.130, 0.125, 0.120, 0.110, 0.105, 0.100, 0.090, 0.088, 0.086, 0.085],
    athlete_churn_year=[0.35, 0.32, 0.30, 0.27, 0.25, 0.23, 0.22, 0.21, 0.21, 0.20],
    deal_rate=[0.14, 0.17, 0.20, 0.24, 0.27, 0.29, 0.30, 0.31, 0.31, 0.32],
    deals_per_athlete=[1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.4, 2.5, 2.5, 2.6],
    avg_deal_eur=[2_200, 2_500, 2_800, 3_100, 3_400, 3_700, 4_000, 4_200, 4_400, 4_600],
    cac_eur=[40, 46, 53, 60, 67, 73, 78, 82, 85, 88],
    max_fan_adds_per_athlete_year=[38, 42, 46, 50, 54, 58, 62, 65, 67, 69],
)


@dataclass
class Assumptions:
    # ---- demand side -------------------------------------------------------
    athletes: list[int] = field(default_factory=lambda: [400, 1_800, 5_500, 13_000, 25_000, 38_000, 52_000, 65_000, 76_000, 85_000])
    # Niche first (no incumbent, acute need), popular entering from Y3 once the
    # niche cohort's earnings make the disintermediation pitch quantified.
    niche_share: list[float] = field(default_factory=lambda: [0.95, 0.92, 0.80, 0.68, 0.58, 0.50, 0.45, 0.43, 0.42, 0.41])
    segments: list[Segment] = field(default_factory=lambda: [NICHE, POPULAR])

    # one-off fan spend (unlocks + tips) as a multiple of subscription GMV
    ppv_tips_multiple: float = 0.35

    # ---- sponsor SaaS ------------------------------------------------------
    sponsors: list[int] = field(default_factory=lambda: [25, 110, 340, 800, 1_500, 2_400, 3_500, 4_600, 5_600, 6_400])
    sponsor_paid_rate: list[float] = field(default_factory=lambda: [0.10, 0.14, 0.17, 0.19, 0.20, 0.20, 0.20, 0.20, 0.20, 0.20])
    sponsor_arpu_month: list[int] = field(default_factory=lambda: [199, 229, 260, 290, 320, 360, 400, 430, 455, 475])
    # A matching product is worth nothing without athletes to match. Below this
    # pool size, paid conversion scales down with supply — otherwise the model
    # books SaaS revenue against an empty directory.
    athletes_for_full_saas_value: int = 2_000

    # ---- take rates --------------------------------------------------------
    take_fan: float = 0.15        # vs OnlyFans 20% — deliberately athlete-friendly
    take_sponsorship: float = 0.10

    # ---- payment rails (charged on GMV, not on our net revenue) ------------
    # Blended card rate for a SPANISH entity, not the US headline. Stripe EEA
    # domestic is 1.5% + EUR 0.25; UK cards 2.5%; non-EEA 3.25%. Assuming a
    # mostly-European fan base with some international tail, 1.9% is the blend.
    # An earlier version of this model used the US 2.9% and overstated the
    # largest cost line in the business by roughly a third.
    psp_pct: float = 0.019
    psp_fixed_eur: float = 0.25
    payout_pct: float = 0.0025
    payout_fixed_eur: float = 0.25
    avg_fan_txn_eur: float = 9.20   # drives how badly the fixed fee bites
    avg_deal_txn_eur: float = 1_800

    # ---- infrastructure (AWS) ---------------------------------------------
    aws_base_month: list[int] = field(default_factory=lambda: [180, 650, 2_100, 5_400, 11_000, 17_000, 24_000, 30_000, 35_000, 39_000])
    # media egress is the cost that separates a content platform from an
    # analytics one. GB per paying fan per month.
    gb_per_fan_month: float = 1.8
    egress_eur_per_gb: float = 0.008   # object storage w/ zero-egress CDN (see 02)
    egress_eur_per_gb_naive: float = 0.075  # CloudFront list — the trap

    # ---- other cost of sales ----------------------------------------------
    moderation_eur_per_1k_items: float = 22.0
    items_per_athlete_month: float = 12.0

    # ---- admission (the gate — business-plan/11-admission-and-matching.md) --
    # Applicants are not athletes. The gate admits a share of them and sends a
    # share to a human, and neither cost existed before admission was built.
    # Note what is NOT changed here: segment `cac_eur` stays as it is, because
    # it was always defined as the cost of landing one athlete ON the platform
    # (see research_data.py). Multiplying it by the funnel would double-count
    # the same money. What is genuinely new is the review labour, which is paid
    # per APPLICATION rather than per athlete.
    #
    # The direct rates are not hand-set: they are the ops-load output of
    # scripts/admission_stress.py under its modelled applicant mix. Retune a
    # threshold in the policy and these move with it.
    admission_rate_direct: float = 0.20
    review_rate_direct: float = 0.25
    # A verified club's nomination lifts an applicant's credibility floor, so
    # more clear on the first pass and fewer need a look. ESTIMATE — no intake
    # data exists; the first federation partnership is what measures it.
    admission_rate_club: float = 0.45
    review_rate_club: float = 0.18
    club_sourced_share: list[float] = field(default_factory=lambda: [0.00, 0.10, 0.20, 0.28, 0.34, 0.38, 0.42, 0.44, 0.46, 0.47])
    review_minutes: float = 4.0
    # Reviewer time is priced off the same loaded salary line the rest of the
    # model uses, rather than a second hand-set wage that could drift from it.
    ops_hours_per_year: int = 1_700

    # ---- operating costs ---------------------------------------------------
    headcount: list[float] = field(default_factory=lambda: [1.5, 3.0, 7.0, 14.0, 24.0, 36.0, 50.0, 62.0, 72.0, 80.0])
    loaded_salary_eur: list[int] = field(default_factory=lambda: [38_000, 52_000, 60_000, 64_000, 66_000, 68_000, 70_000, 72_000, 74_000, 76_000])
    sponsor_cac_eur: list[int] = field(default_factory=lambda: [900, 1_050, 1_200, 1_400, 1_600, 1_750, 1_900, 2_000, 2_100, 2_200])
    legal_compliance_eur: list[int] = field(default_factory=lambda: [18_000, 45_000, 90_000, 150_000, 200_000, 235_000, 270_000, 300_000, 325_000, 345_000])
    other_opex_pct_of_revenue: float = 0.08

    # ---- financing / valuation --------------------------------------------
    tax_rate: float = 0.15         # Spanish Startup Law: 15% for first 4 profitable years
    wacc: float = 0.25
    terminal_growth: float = 0.03
    risk_free: float = 0.032       # Spanish 10Y, mid-2026
    founder_alt_return: float = 0.07


A = Assumptions()


def i(n: int) -> int:
    """Year number (1-10) -> list index."""
    return n - 1


# ─────────────────────────────────────────────────────────────────────────────
# Model
# ─────────────────────────────────────────────────────────────────────────────

def fan_path(start: float, target_end: float, churn: float,
              max_monthly_adds: float = float("inf")) -> dict:
    """Twelve months of cohort decay, solved for the gross adds that land on the
    target year-end count.

        fans[t+1] = fans[t] * (1 - churn) + adds

    so after 12 months, with r = 1 - churn:

        end = start * r^12 + adds * (1 - r^12) / (1 - r)

    Two things fall out of this that a net-stock model cannot see:

    1.  **Revenue accrues on the AVERAGE fan count, not the year-end count.**
        Charging twelve months at the December number overstates revenue by
        roughly a third during fast growth. The previous version did exactly
        that.
    2.  **Gross adds are far larger than net adds.** At 9%/month, a cohort
        retains 0.91^12 = 32% over a year, so most of next year's fans are
        replacements for this year's. That is the real acquisition load, and it
        is invisible until churn is modelled explicitly.
    """
    r = 1.0 - churn
    stock_survivors = start * r ** 12
    denom = (1 - r ** 12) / (1 - r) if churn > 0 else 12.0
    required = max(0.0, (target_end - stock_survivors) / denom)
    # Capacity binds before the target does when churn is high.
    monthly_adds = min(required, max_monthly_adds)

    fans, total, churned = start, 0.0, 0.0
    for _ in range(12):
        churned += fans * churn
        fans = fans * r + monthly_adds
        total += fans
    return {
        "avg": total / 12, "end": fans,
        "gross_adds": monthly_adds * 12, "churned": churned,
        "retained_share": (stock_survivors / start) if start else 0.0,
        "capacity_bound": monthly_adds < required - 1e-9,
        "shortfall": max(0.0, target_end - fans),
    }


def segment_year(seg: Segment, athlete_count: float, prev_athletes: float,
                 prev_fans: float, i_: int) -> dict:
    """One segment's contribution in one year, with cohort churn on both sides."""
    monetising = athlete_count * seg.monetise_rate[i_]
    target_fans = monetising * seg.fans_per_athlete[i_]
    cap_monthly = monetising * seg.max_fan_adds_per_athlete_year[i_] / 12
    fans = fan_path(prev_fans, target_fans, seg.fan_churn_month[i_], cap_monthly)

    # Revenue on the AVERAGE fan count — the honest basis.
    sub_gmv = fans["avg"] * seg.fan_arpu_month[i_] * 12
    fan_gmv = sub_gmv * (1 + A.ppv_tips_multiple)

    deals = athlete_count * seg.deal_rate[i_] * seg.deals_per_athlete[i_]
    sponsorship_gmv = deals * seg.avg_deal_eur[i_]

    # Athletes churn too, so acquisition must replace them before it grows the
    # base. Gross adds, not net, are what marketing actually pays for.
    churn_a = seg.athlete_churn_year[i_]
    athlete_gross_adds = max(0.0, athlete_count - prev_athletes * (1 - churn_a))
    athletes_lost = prev_athletes * churn_a

    return dict(
        name=seg.name, athletes=athlete_count, paying_fans=fans["end"],
        avg_fans=fans["avg"], fan_gross_adds=fans["gross_adds"],
        fans_churned=fans["churned"], fan_retained_share=fans["retained_share"],
        capacity_bound=fans["capacity_bound"], fan_shortfall=fans["shortfall"],
        athlete_gross_adds=athlete_gross_adds, athletes_lost=athletes_lost,
        deals=deals, fan_gmv=fan_gmv, sponsorship_gmv=sponsorship_gmv,
        revenue=fan_gmv * A.take_fan + sponsorship_gmv * A.take_sponsorship,
    )


def split(i_: int) -> dict[str, float]:
    """Athletes per segment in a given year."""
    total = A.athletes[i_]
    n = total * A.niche_share[i_]
    return {"niche": n, "popular": total - n}


def build() -> list[dict]:
    rows = []
    prev_fans = {s.name: 0.0 for s in A.segments}
    for y in YEARS:
        i_ = i(y)
        athletes = A.athletes[i_]
        counts = split(i_)
        prev_counts = split(i_ - 1) if y > 1 else {s.name: 0.0 for s in A.segments}
        segs = [segment_year(s, counts[s.name], prev_counts[s.name],
                             prev_fans[s.name], i_) for s in A.segments]
        prev_fans = {s["name"]: s["paying_fans"] for s in segs}

        paying_fans = sum(s["paying_fans"] for s in segs)
        deals = sum(s["deals"] for s in segs)
        fan_gmv = sum(s["fan_gmv"] for s in segs)
        sponsorship_gmv = sum(s["sponsorship_gmv"] for s in segs)
        gmv = fan_gmv + sponsorship_gmv

        # --- net revenue ------------------------------------------------
        rev_fan = fan_gmv * A.take_fan
        rev_sponsorship = sponsorship_gmv * A.take_sponsorship
        supply_factor = min(1.0, athletes / A.athletes_for_full_saas_value)
        paying_sponsors = A.sponsors[i_] * A.sponsor_paid_rate[i_] * supply_factor
        rev_saas = paying_sponsors * A.sponsor_arpu_month[i_] * 12
        revenue = rev_fan + rev_sponsorship + rev_saas

        # --- cost of sales ---------------------------------------------
        fan_txns = fan_gmv / A.avg_fan_txn_eur
        deal_txns = sponsorship_gmv / A.avg_deal_txn_eur
        psp = (gmv * A.psp_pct) + (fan_txns + deal_txns) * A.psp_fixed_eur
        payouts = (gmv * A.payout_pct) + (fan_txns / 30 + deal_txns) * A.payout_fixed_eur

        egress_gb = paying_fans * A.gb_per_fan_month * 12
        infra = A.aws_base_month[i_] * 12 + egress_gb * A.egress_eur_per_gb
        infra_naive = A.aws_base_month[i_] * 12 + egress_gb * A.egress_eur_per_gb_naive

        items = athletes * A.items_per_athlete_month * 12
        moderation = items / 1000 * A.moderation_eur_per_1k_items

        # --- admission: applications behind each athlete, and the review bill -
        # Sits in cost of sales beside moderation on purpose. The two are the
        # same obligation on opposite sides of the marketplace — vetting who is
        # on it, and vetting what they post — so splitting them across the
        # gross-margin line would be arbitrary.
        club_share = A.club_sourced_share[i_]
        athlete_gross_adds = sum(s_["athlete_gross_adds"] for s_ in segs)
        marketing_athletes = sum(s_["athlete_gross_adds"] * seg.cac_eur[i_]
                                 for seg, s_ in zip(A.segments, segs))
        admit_rate = (club_share * A.admission_rate_club
                      + (1 - club_share) * A.admission_rate_direct)
        review_rate = (club_share * A.review_rate_club
                       + (1 - club_share) * A.review_rate_direct)
        applications = athlete_gross_adds / admit_rate if admit_rate else 0.0
        reviews = applications * review_rate
        review_hourly = A.loaded_salary_eur[i_] / A.ops_hours_per_year
        verification = reviews * (A.review_minutes / 60) * review_hourly
        review_fte = reviews * (A.review_minutes / 60) / A.ops_hours_per_year
        # Memo, not a cost: segment CAC is priced per athlete ADMITTED, so this
        # is what the same money works out to per application. It is the figure
        # to hold against what a channel actually charges — if a federation
        # mailing costs more per name than this, the CAC line is understated.
        cac_per_application = (marketing_athletes / applications) if applications else 0.0

        cogs = psp + payouts + infra + moderation + verification
        gross = revenue - cogs

        # --- opex -------------------------------------------------------
        people = A.headcount[i_] * A.loaded_salary_eur[i_]
        # CAC is per segment: displacing an agent costs more than reaching an
        # athlete who has no representation at all.
        # GROSS adds, not net: churned athletes must be replaced before the base
        # grows at all, and that replacement is paid for at full CAC.
        by_name = {s["name"]: s for s in segs}
        marketing = sum(by_name[s.name]["athlete_gross_adds"] * s.cac_eur[i_] for s in A.segments)
        new_sponsors = A.sponsors[i_] - (A.sponsors[i_ - 1] if y > 1 else 0)
        marketing += max(new_sponsors, 0) * A.sponsor_cac_eur[i_]
        legal = A.legal_compliance_eur[i_]
        other = revenue * A.other_opex_pct_of_revenue
        opex = people + marketing + legal + other

        ebitda = gross - opex
        tax = max(0.0, ebitda) * A.tax_rate
        fcf = ebitda - tax

        rows.append(dict(
            year=y, athletes=athletes, paying_fans=paying_fans, deals=deals,
            paying_sponsors=paying_sponsors, gmv=gmv, fan_gmv=fan_gmv,
            sponsorship_gmv=sponsorship_gmv, rev_fan=rev_fan,
            rev_sponsorship=rev_sponsorship, rev_saas=rev_saas, revenue=revenue,
            psp=psp, payouts=payouts, infra=infra, infra_naive=infra_naive,
            moderation=moderation, verification=verification,
            applications=applications, reviews=reviews, admit_rate=admit_rate,
            review_fte=review_fte, cac_per_application=cac_per_application,
            review_rate=review_rate, review_hourly=review_hourly,
            cogs=cogs, gross=gross, people=people,
            marketing=marketing, legal=legal, other=other, opex=opex,
            ebitda=ebitda, tax=tax, fcf=fcf,
            headcount=A.headcount[i_],
            segs={s["name"]: s for s in segs},
            niche_share=A.niche_share[i_],
            avg_fans=sum(s["avg_fans"] for s in segs),
            fan_gross_adds=sum(s["fan_gross_adds"] for s in segs),
            fans_churned=sum(s["fans_churned"] for s in segs),
            athlete_gross_adds=sum(s["athlete_gross_adds"] for s in segs),
            athletes_lost=sum(s["athletes_lost"] for s in segs),
        ))
    return rows


def valuation(rows: list[dict]) -> dict:
    pv = sum(r["fcf"] / (1 + A.wacc) ** r["year"] for r in rows)
    tv = rows[-1]["fcf"] * (1 + A.terminal_growth) / (A.wacc - A.terminal_growth)
    pv_tv = tv / (1 + A.wacc) ** rows[-1]["year"]
    ev = pv + pv_tv
    return dict(pv_explicit=pv, terminal_value=tv, pv_terminal=pv_tv, enterprise_value=ev)


# ─────────────────────────────────────────────────────────────────────────────
# Rendering
# ─────────────────────────────────────────────────────────────────────────────

def eur(x: float, dp: int = 0) -> str:
    if abs(x) >= 1_000_000:
        return f"€{x/1_000_000:,.2f}M"
    if abs(x) >= 1_000:
        return f"€{x/1_000:,.0f}k"
    return f"€{x:,.{dp}f}"


def num(x: float) -> str:
    return f"{x:,.0f}"


def table(head: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(head) + " |",
           "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def render(rows: list[dict]) -> dict[str, str]:
    ys = [f"Y{r['year']}" for r in rows]

    def line(label, key, fmt=eur):
        return [label] + [fmt(r[key]) for r in rows]

    drivers = table(["Driver"] + ys, [
        line("Active athletes", "athletes", num),
        line("Paying fans", "paying_fans", num),
        line("Sponsorship deals", "deals", num),
        line("Paying sponsors (SaaS)", "paying_sponsors", num),
        line("Headcount (FTE)", "headcount", lambda v: f"{v:,.1f}"),
    ])

    gmv = table(["Marketplace volume"] + ys, [
        line("Fan GMV (subs + unlocks)", "fan_gmv"),
        line("Sponsorship GMV", "sponsorship_gmv"),
        line("**Total GMV**", "gmv"),
    ])

    revenue = table(["Net revenue"] + ys, [
        line(f"Fan take ({A.take_fan:.0%})", "rev_fan"),
        line(f"Sponsorship take ({A.take_sponsorship:.0%})", "rev_sponsorship"),
        line("Sponsor SaaS", "rev_saas"),
        line("**Total net revenue**", "revenue"),
    ])

    pl = table(["P&L"] + ys, [
        line("Net revenue", "revenue"),
        line("Payment processing", "psp"),
        line("Payouts", "payouts"),
        line("Infrastructure (AWS)", "infra"),
        line("Moderation", "moderation"),
        line("Athlete verification", "verification"),
        line("**Gross profit**", "gross"),
        ["Gross margin"] + [f"{(r['gross']/r['revenue']*100 if r['revenue'] else 0):,.0f}%" for r in rows],
        line("People", "people"),
        line("Marketing / CAC", "marketing"),
        line("Legal & compliance", "legal"),
        line("Other opex", "other"),
        line("**EBITDA**", "ebitda"),
        line("Tax", "tax"),
        line("**Free cash flow**", "fcf"),
    ])

    egress = table(["Egress strategy"] + ys, [
        line("AWS w/ zero-egress CDN", "infra"),
        line("AWS w/ CloudFront list price", "infra_naive"),
        ["**Annual difference**"] + [eur(r["infra_naive"] - r["infra"]) for r in rows],
    ])

    v = valuation(rows)
    val = table(["Valuation (DCF)", "Value"], [
        ["PV of explicit FCF, Y1–Y7", eur(v["pv_explicit"])],
        [f"Terminal value (g={A.terminal_growth:.0%})", eur(v["terminal_value"])],
        ["PV of terminal value", eur(v["pv_terminal"])],
        [f"**Enterprise value (WACC {A.wacc:.0%})**", f"**{eur(v['enterprise_value'])}**"],
    ])

    last = rows[-1]
    df = (1 + A.wacc) ** last["year"]   # discount Y7 money back to today
    mult = table(["Exit method (Y7)", "Multiple", "Value AT Y7", "Discounted to today"], [
        ["Marketplace comparables", "4.0x revenue", eur(last["revenue"] * 4), eur(last["revenue"] * 4 / df)],
        ["Blended marketplace + SaaS", "6.5x revenue", eur(last["revenue"] * 6.5), eur(last["revenue"] * 6.5 / df)],
        ["High-growth SaaS mix", "9.0x revenue", eur(last["revenue"] * 9), eur(last["revenue"] * 9 / df)],
        ["EBITDA multiple", "14x EBITDA", eur(max(last["ebitda"], 0) * 14), eur(max(last["ebitda"], 0) * 14 / df)],
    ])

    # cumulative funding need = deepest point of cumulative FCF
    cum, trough, trough_year = 0.0, 0.0, 1
    cash_rows = []
    for r in rows:
        cum += r["fcf"]
        if cum < trough:
            trough, trough_year = cum, r["year"]
        cash_rows.append([f"Y{r['year']}", eur(r["fcf"]), eur(cum)])
    cash = table(["Year", "Free cash flow", "Cumulative"], cash_rows)

    funding = table(["Capital requirement", "Value"], [
        ["Deepest cumulative cash position", eur(trough)],
        ["Year it occurs", f"Y{trough_year}"],
        ["Buffer at 40% (hiring slips, churn worse)", eur(abs(trough) * 0.4)],
        ["**Total capital to fund the plan**", f"**{eur(abs(trough) * 1.4)}**"],
        ["First EBITDA-positive year", f"Y{next((r['year'] for r in rows if r['ebitda'] > 0), 0)}"],
    ])

    churn = table(["Retention & acquisition"] + ys, [
        line("Paying fans, year end", "paying_fans", num),
        line("Paying fans, average", "avg_fans", num),
        line("Fans acquired (gross)", "fan_gross_adds", num),
        line("Fans lost to churn", "fans_churned", num),
        line("Athletes acquired (gross)", "athlete_gross_adds", num),
        line("Athletes lost to churn", "athletes_lost", num),
    ])

    seg_rows = []
    for key, label in (("niche", "Niche (market creation)"), ("popular", "Popular (disintermediation)")):
        seg_rows.append([f"**{label}**"] + ["" for _ in rows])
        seg_rows.append(["  Athletes"] + [num(r["segs"][key]["athletes"]) for r in rows])
        seg_rows.append(["  Paying fans"] + [num(r["segs"][key]["paying_fans"]) for r in rows])
        seg_rows.append(["  Deals"] + [num(r["segs"][key]["deals"]) for r in rows])
        seg_rows.append(["  Net revenue"] + [eur(r["segs"][key]["revenue"]) for r in rows])
    seg_rows.append(["**Niche share of athletes**"] + [f"{r['niche_share']:.0%}" for r in rows])
    seg_rows.append(["**Niche share of revenue**"] + [
        f"{r['segs']['niche']['revenue'] / (r['segs']['niche']['revenue'] + r['segs']['popular']['revenue']):.0%}"
        for r in rows])
    segments = table(["Segment"] + ys, seg_rows)

    return dict(drivers=drivers, gmv=gmv, revenue=revenue, pl=pl, egress=egress,
                valuation=val, multiples=mult, cash=cash, funding=funding,
                segments=segments, churn=churn)


def unit_economics() -> str:
    """The fixed-fee problem, per transaction size."""
    rows = []
    for price in (4.99, 9.99, 14.99, 24.99, 99.00):
        take = price * A.take_fan
        psp = price * A.psp_pct + A.psp_fixed_eur
        net = take - psp
        rows.append([
            f"€{price:,.2f}",
            f"€{take:,.2f}",
            f"€{psp:,.2f}",
            f"€{net:,.2f}",
            f"{(net/take*100 if take else 0):,.0f}%",
        ])
    return table(
        ["Fan pays (monthly)", f"Our take ({A.take_fan:.0%})", "Payment cost", "We keep", "% of take retained"],
        rows,
    )


DOC_TABLES = {
    "03-financial-model.md": ["drivers", "churn", "segments", "gmv", "revenue", "pl", "cash", "funding"],
    "04-capital-and-valuation.md": ["valuation", "multiples"],
}


def write_docs(rendered: dict[str, str]) -> None:
    """Replace the content between <!-- MODEL:key --> and <!-- /MODEL:key -->.

    The narrative stays hand-written and in control of what is shown; only the
    tables are generated. Three rounds of propagating numbers by hand was
    enough — a figure that appears in a document should come from the model that
    produced it.
    """
    import pathlib
    here = pathlib.Path(__file__).parent
    for filename, keys in DOC_TABLES.items():
        path = here / filename
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        for key in keys:
            start, end = f"<!-- MODEL:{key} -->", f"<!-- /MODEL:{key} -->"
            if start not in text or end not in text:
                continue
            head, _, rest = text.partition(start)
            _, _, tail = rest.partition(end)
            text = head + start + "\n" + rendered[key] + "\n" + end + tail
        path.write_text(text, encoding="utf-8")
        print(f"wrote {filename}")


def main() -> None:
    rows = build()
    r = render(rows)
    print("\n## Drivers\n\n" + r["drivers"])
    print("\n## Retention & acquisition\n\n" + r["churn"])
    print("\n## Segments\n\n" + r["segments"])
    print("\n## GMV\n\n" + r["gmv"])
    print("\n## Net revenue\n\n" + r["revenue"])
    print("\n## P&L\n\n" + r["pl"])
    print("\n## Egress strategy\n\n" + r["egress"])
    print("\n## Unit economics per subscription tier\n\n" + unit_economics())
    print("\n## Cash\n\n" + r["cash"])
    print("\n## Capital requirement\n\n" + r["funding"])
    print("\n## Valuation\n\n" + r["valuation"])
    print("\n" + r["multiples"])

    if "--write" in sys.argv:
        print()
        write_docs(r)


if __name__ == "__main__":
    main()
